function R58=main_step58_reflection_paired_matched_edi(varargin)
%MAIN_STEP58_REFLECTION_PAIRED_MATCHED_EDI
% ONE no-solve EDI extraction on the already solved Step57 reflection-
% paired symmetric FEM field, using the EXACT Step48 absolute annulus.
%
% No FEM solve, no mesh generation, no remeshing, no radius sweep.
% The existing audited Step45 postprocessor performs exactly one
% 16-point FE-nodal-q interaction EDI with:
%   r_inner = Step48 matched absolute inner radius
%   r_outer = Step48 matched absolute outer radius (=0.65*a0)
%
% Output compares actual FEM EDI residuals from:
%   Step45 original symmetric mesh
%   Step47 refined but unpaired mesh
%   Step57 reflection-paired mesh
%
% Usage:
%   addpath(genpath(pwd));
%   R58=main_step58_reflection_paired_matched_edi();
%   disp(R58.comparison);
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
vdir=fullfile(root,'verification');
ip=inputParser;
addParameter(ip,'Step48File', ...
    fullfile(vdir,'step48_refined_matched_edi_comparison_small_data.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'Step57Checkpoint', ...
    fullfile(vdir,'step57_reflection_paired_symmetric_theta0_solved.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'Step57CODFile', ...
    fullfile(vdir,'step57_reflection_paired_symmetric_field_leakage_small_data.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'SavePrefix', ...
    fullfile(vdir,'step58_reflection_paired_matched_edi'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
parse(ip,varargin{:});
opt=ip.Results;
addpath(genpath(root));

f48=char(opt.Step48File);
cp57=char(opt.Step57Checkpoint);
cod57=char(opt.Step57CODFile);
prefix=char(opt.SavePrefix);
if exist(f48,'file')~=2
    error('step58:MissingStep48','Missing completed Step48 comparison file.');
end
if exist(cp57,'file')~=2
    error('step58:MissingStep57','Missing solved Step57 checkpoint.');
end
if exist(cod57,'file')~=2
    error('step58:MissingStep57COD','Missing completed Step57 COD-only result.');
end

a=load(f48,'R48');
b=load(cp57,'meta','a0');
c=load(cod57,'O45');
if ~isfield(a,'R48')||~isfield(b,'meta')||~isfield(b,'a0')|| ...
        ~isfield(c,'O45')
    error('step58:BadSavedInput','Saved audit inputs have unexpected format.');
end
R48=a.R48;
meta=b.meta;
O57cod=c.O45;

if ~isfield(R48,'comparison')||~istable(R48.comparison)|| ...
        height(R48.comparison)~=2 || ...
        ~all(ismember({'field','KI','KII','ratio','r_inner','r_outer'}, ...
                      R48.comparison.Properties.VariableNames))
    error('step58:BadStep48','Step48 matched comparison table is invalid.');
end
if ~isfield(meta,'stage') || ...
        ~strcmp(meta.stage,'step57_reflection_paired_control') || ...
        ~strcmp(meta.caseType,'step45_centered_half_theta0') || ...
        meta.Npoly~=240 || meta.zeroAngleDeg~=0 || ...
        meta.nT3~=2578 || meta.nT6~=5427 || ...
        ~isfield(meta,'exactMeshReused') || ~meta.exactMeshReused || ...
        ~isfield(meta,'EDIperformed') || meta.EDIperformed || ...
        abs(b.a0-.004)>1e-12
    error('step58:WrongStep57Checkpoint', ...
        'Expected exact saved reflection-paired Step57 symmetric control.');
end
if ~isfield(O57cod,'CODgates') || ~O57cod.CODgates.evaluated || ...
        ~O57cod.CODgates.passed || ...
        O57cod.CODgates.maxAbsRatio>1e-10 || ...
        ~isfield(O57cod,'faceGridMismatch') || ...
        O57cod.faceGridMismatch>1e-12
    error('step58:Step57CODNotVerified', ...
        'Step57 COD roundoff-symmetry result is missing or inconsistent.');
end

ri=R48.comparison.r_inner(1);
ro=R48.comparison.r_outer(1);
if max(abs(R48.comparison.r_inner-ri))>1e-12 || ...
        max(abs(R48.comparison.r_outer-ro))>1e-12 || ...
        ~all(isfinite([ri,ro])) || ri<=0 || ro<=ri || ...
        abs(ro/b.a0-.65)>1e-12
    error('step58:UnmatchedAnnulus', ...
        'Step48 comparison does not define one common physical 0.65*a0 annulus.');
end
if isfield(R48,'matchedInner') && abs(R48.matchedInner-ri)>1e-12
    error('step58:InnerRadiusMismatch','R48 stored matched inner radius differs.');
end
if isfield(R48,'matchedOuter') && abs(R48.matchedOuter-ro)>1e-12
    error('step58:OuterRadiusMismatch','R48 stored matched outer radius differs.');
end

% Independent Step57 tip-scale guard: exact old annulus must remain admissible.
hTip=O57cod.tipEdgeMedian;
if ~isfinite(hTip) || ri<2*hTip || ri>=ro
    error('step58:Step57AnnulusInadmissible', ...
        'Exact Step48 annulus is invalid for the Step57 tip scale.');
end

fprintf('\n============================================================\n');
fprintf('STEP 58: ONE MATCHED EDI ON REFLECTION-PAIRED STEP57 FIELD\n');
fprintf('============================================================\n');
fprintf('  Step57 solved mesh: T3=%d, T6=%d; COD max |KII/KI|=%.9e.\n', ...
    meta.nT3,meta.nT6,O57cod.CODgates.maxAbsRatio);
fprintf('  EXACT Step48 annulus: r_inner=%.12g m, r_outer=%.12g m.\n',ri,ro);
fprintf('  Step57 2*hTip=%.12g m; annulus admissible.\n',2*hTip);
fprintf('  ONE 16-point FE-nodal-q EDI only. NO solve, mesh, remesh or sweep.\n');

% Use the already audited EDI implementation. It will repeat the cheap
% native-COD diagnostics first, then execute exactly the requested domain.
O57edi=main_step45_symmetric_field_leakage(cp57, ...
    'RunEDI',true, ...
    'ROuterOverA0',ro/b.a0, ...
    'InnerRadius',ri, ...
    'SavePrefix',prefix);

if ~isfield(O57edi,'EDI') || ~O57edi.EDI.performed || ...
        ~istable(O57edi.EDI.table) || height(O57edi.EDI.table)~=1
    error('step58:MissingEDI','Expected exactly one completed Step57 EDI result.');
end
E=O57edi.EDI.table;
if abs(E.r_inner(1)-ri)>1e-12 || ...
        abs(E.r_outer_over_a0(1)-ro/b.a0)>1e-12 || ...
        ~all(isfinite([E.KI(1),E.KII(1),E.ratio(1)])) || E.KI(1)<=0
    error('step58:WrongEDIResult', ...
        'Step57 EDI result is not the exact matched Step48 annulus.');
end

old=R48.comparison;
T=table( ...
    [old.field;{'Paired Step57'}], ...
    [old.KI;E.KI(1)], ...
    [old.KII;E.KII(1)], ...
    [old.ratio;E.ratio(1)], ...
    repmat(ri,3,1), ...
    repmat(ro,3,1), ...
    'VariableNames',{'field','KI','KII','ratio','r_inner','r_outer'});

q45=T.ratio(1);
q47=T.ratio(2);
q57=T.ratio(3);
fprintf('\nMATCHED ACTUAL-FEM SYMMETRIC EDI: SAME ABSOLUTE ANNULUS\n');
disp(T);
fprintf('  |q57| / |q47| = %.9e\n',abs(q57)/abs(q47));
fprintf('  |q57| / |q45| = %.9e\n',abs(q57)/abs(q45));
fprintf('  COD Step57 max |q| = %.9e\n',O57cod.CODgates.maxAbsRatio);
fprintf(['  Do NOT subtract these symmetry residuals from the separate ', ...
    'asymmetric physical result.\n']);

R58=struct('comparison',T, ...
    'step57EDI',O57edi.EDI, ...
    'step57CODmaxAbsRatio',O57cod.CODgates.maxAbsRatio, ...
    'matchedInner',ri,'matchedOuter',ro, ...
    'ratioAbsRelativeToStep47',abs(q57)/abs(q47), ...
    'ratioAbsRelativeToStep45',abs(q57)/abs(q45), ...
    'noNewFEM',true,'noMesh',true,'singleEDIDomain',true, ...
    'interpretation',['Actual symmetric FEM extractor control only; ', ...
      'not an uncertainty correction for asymmetric KII.']);
save([prefix '_comparison_small_data.mat'],'R58');
fprintf('  Compact Step58 comparison saved; NO FEM solve occurred.\n');
end
