function R=main_step62b_mesh_calibration(varargin)
%MAIN_STEP62B_MESH_CALIBRATION
% Small no-solve calibration study for the Step62 exterior grading.
%
% Scientific rule:
%   calibrate ONLY mesh geometry/quality, never physical KI/KII.
%
% The structured 6-mm reflection-paired core is held fixed. This driver:
%   1) diagnoses the exact worst adjacent-size jump in the archived
%      Step62 baseline candidate;
%   2) evaluates a small predeclared grid of exterior transition laws;
%   3) ranks only candidates that pass all structural gates, including
%      max adjacent characteristic-size ratio <= 1.8;
%   4) runs prescribed-field controls on the best TWO only;
%   5) writes one exact selected candidate only if those controls pass.
%
% No physical U is loaded by the Step62 builder. No FEM solve is called.
%
% Usage:
%   addpath(genpath(pwd));
%   R = main_step62b_mesh_calibration();
%   disp(R.baselineWorstNeighbors(1:min(10,height(R.baselineWorstNeighbors)),:));
%   disp(R.calibrationTable);
%   disp(R.syntheticTable);
%
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
vdir=fullfile(root,'verification');
ip=inputParser;
addParameter(ip,'BaselineCandidate', ...
    fullfile(vdir,'step62_structured_graded_mesh_candidate_T3.mat'), ...
    @(x)ischar(x)||(isstring(x)&&isscalar(x)));
addParameter(ip,'CheckpointFile', ...
    fullfile(vdir,'step38_tip_refined_solved.mat'), ...
    @(x)ischar(x)||(isstring(x)&&isscalar(x)));
addParameter(ip,'SavePrefix', ...
    fullfile(vdir,'step62b_mesh_calibration'), ...
    @(x)ischar(x)||(isstring(x)&&isscalar(x)));
addParameter(ip,'Visible','off',@(x)ischar(x)||isstring(x));
parse(ip,varargin{:}); opt=ip.Results;
addpath(genpath(root));

assert_audit_branch(root);
baseFile=char(opt.BaselineCandidate);
cp=char(opt.CheckpointFile);
prefix=char(opt.SavePrefix);
if exist(baseFile,'file')~=2
    error('step62b:MissingBaseline', ...
        'Missing archived Step62 baseline candidate: %s',baseFile);
end
if exist(cp,'file')~=2
    error('step62b:MissingCheckpoint','Missing Step38 checkpoint: %s',cp);
end

d=load(baseFile,'candidate');
if ~isfield(d,'candidate')
    error('step62b:BadBaseline','Baseline MAT does not contain candidate.');
end
base=d.candidate;
for f={'p','t','pairedElementIDs','exteriorElementIDs','provenance'}
    need(base,f{1});
end
if ~isfield(base.provenance,'sourceCommit') || ...
        ~contains(base.provenance.sourceCommit,'1d1b778')
    warning('step62b:BaselineCommit', ...
        ['Baseline provenance sourceCommit is not the short Codex commit ', ...
         'label 1d1b778; continuing because exact candidate bytes are used.']);
end

fprintf('\n============================================================\n');
fprintf('STEP 62B: EXTERIOR-MESH CALIBRATION — NO PHYSICAL FEM\n');
fprintf('============================================================\n');
fprintf('  Baseline candidate: %s\n',baseFile);
fprintf('  Structured 6-mm core topology is NOT calibrated here.\n');
fprintf('  Objective: reduce adjacent-size jump without using physical KI/KII.\n');

% Verify that parameterization itself did not change the historical
% Step62 default geometry. "verbose=false" is non-geometric.
tmp=fullfile(vdir,'step62b_default_reproduction_tmp.mat');
if exist(tmp,'file')==2,delete(tmp);end
main_step62_structured_graded_mesh( ...
    'CheckpointFile',cp, ...
    'SavePrefix',fullfile(vdir,'step62b_default_reproduction'), ...
    'RunSynthetic',false, ...
    'ExteriorCalibration',struct('verbose',false), ...
    'WriteArtifacts',false, ...
    'Verbose',false, ...
    'DebugFile',tmp, ...
    'Level',0);
q=load(tmp,'candidateMesh');delete(tmp);
baselineReproduced=isequal(q.candidateMesh.coord3,base.p)&& ...
    isequal(q.candidateMesh.connect3,base.t);
assert(baselineReproduced,'step62b:BaselineNotReproduced', ...
    ['Parameterizing the exterior changed the default Step62 geometry. ', ...
     'Stop before calibration.']);
fprintf('  Default-parameter reproduction of archived Step62: exact PASS.\n');

% -------------------------------------------------------------------------
% A. Locate the baseline 2.311... adjacent-size jump exactly.
% -------------------------------------------------------------------------
baselineWorst=neighbor_pair_table(base.p,base.t,base.crack, ...
    base.pairedElementIDs,base.exteriorElementIDs,20);
fprintf('\nBASELINE WORST ADJACENT-SIZE PAIRS\n');
disp(baselineWorst(1:min(10,height(baselineWorst)),:));
fprintf('  Baseline maximum adjacent-size ratio = %.12g\n',baselineWorst.ratio(1));

% -------------------------------------------------------------------------
% B. Small predeclared calibration grid.
% Hold core/rp/tip law fixed. Vary ONLY exterior transition length and
% far-field growth slope. Boundary metric growth and hard ratio target are
% fixed prospectively for this calibration.
% -------------------------------------------------------------------------
transition_mm=[6 8 10 12];
farSlope=[.10 .15];
n=numel(transition_mm)*numel(farSlope);
rows=cell(n,1);
params=cell(n,1);
idx=0;
for i=1:numel(transition_mm)
    for j=1:numel(farSlope)
        idx=idx+1;
        cal=struct( ...
            'transitionLength_m',transition_mm(i)*1e-3, ...
            'farSlope',farSlope(j), ...
            'boundaryMetricGrowth',.25, ...
            'smoothingSteps',6, ...
            'refinementMaxPasses',140, ...
            'refinementMinAngle_deg',25, ...
            'refinementLongestFactor',1.65, ...
            'neighborRatioTarget',1.8, ...
            'verbose',false);
        params{idx}=cal;
        fprintf('\n------------------------------------------------------------\n');
        fprintf('CALIBRATION C%02d: L=%.1f mm, farSlope=%.3f\n', ...
            idx,transition_mm(i),farSlope(j));
        try
            O=main_step62_structured_graded_mesh( ...
                'CheckpointFile',cp, ...
                'SavePrefix',sprintf('%s_C%02d',prefix,idx), ...
                'Visible','off', ...
                'RunSynthetic',false, ...
                'ExteriorCalibration',cal, ...
                'WriteArtifacts',false, ...
                'Verbose',false, ...
                'Level',0);
            hardPass=hard_structural_pass(O.gates);
            row=struct( ...
                'candidate',string(sprintf('C%02d',idx)), ...
                'transitionLength_mm',transition_mm(i), ...
                'farSlope',farSlope(j), ...
                'boundaryMetricGrowth',cal.boundaryMetricGrowth, ...
                'neighborRatioTarget',cal.neighborRatioTarget, ...
                'hardStructuralPass',hardPass, ...
                'structuralPass',logical(O.gates.structuralPass), ...
                'maxNeighborRatio',O.maxNeighborSizeRatio, ...
                'newT3',O.summary.newT3, ...
                'newT6Nodes',O.summary.newT6Nodes, ...
                'patchMinAngle_deg',O.summary.patchMinAngle_deg, ...
                'exteriorMinAngle_deg',O.summary.exteriorMinAngle_deg, ...
                'candidateSupportInsidePaired', ...
                    logical(O.gates.candidateSupportInsidePairedRegion), ...
                'exteriorOutsideSupport',logical(O.gates.exteriorOutsideSupport), ...
                'tipFanSixTriangles',logical(O.gates.tipFanSixTriangles), ...
                'nativeSamplingAdequate',logical(O.gates.nativeSamplingAdequate), ...
                'error',"");
        catch ME
            row=failed_row(idx,transition_mm(i),farSlope(j),cal,ME);
        end
        rows{idx}=row;
    end
end
calTable=struct2table(vertcat(rows{:}));
calTable.ratioPass=calTable.maxNeighborRatio<=1.8;
% Lexicographic scientific ranking:
% hard gates -> ratio <=1.8 -> smallest ratio -> fewer T3.
rankKey=[~calTable.hardStructuralPass,~calTable.ratioPass, ...
    calTable.maxNeighborRatio,calTable.newT3];
[~,ord]=sortrows(rankKey,[1 2 3 4]);
calTable.rank=zeros(height(calTable),1);
calTable.rank(ord)=(1:height(calTable))';
calTable=sortrows(calTable,'rank');

fprintf('\nCALIBRATION TABLE — MESH METRICS ONLY\n');
disp(calTable);

eligible=find(calTable.structuralPass & calTable.ratioPass);
if isempty(eligible)
    R=finalize_no_selection(prefix,baselineWorst,calTable,params, ...
        ['No candidate met all structural gates including ', ...
         'max adjacent-size ratio <= 1.8. No synthetic controls run.']);
    fprintf('STOP: no candidate passed the predeclared 1.8 grading gate.\n');
    return
end

% -------------------------------------------------------------------------
% C. Prescribed fields on best TWO structural candidates only.
% -------------------------------------------------------------------------
nSyn=min(2,numel(eligible));
synRows=cell(nSyn,1);
synObjects=cell(nSyn,1);
for k=1:nSyn
    tableRow=eligible(k);
    id=sscanf(char(calTable.candidate(tableRow)),'C%d');
    cal=params{id};
    fprintf('\n============================================================\n');
    fprintf('SYNTHETIC QUALIFICATION %d/%d: %s\n', ...
        k,nSyn,calTable.candidate(tableRow));
    fprintf('============================================================\n');
    O=main_step62_structured_graded_mesh( ...
        'CheckpointFile',cp, ...
        'SavePrefix',sprintf('%s_%s_syn',prefix,calTable.candidate(tableRow)), ...
        'Visible','off', ...
        'RunSynthetic',true, ...
        'ExteriorCalibration',cal, ...
        'WriteArtifacts',false, ...
        'Verbose',false, ...
        'Level',0);
    synObjects{k}=O.synthetic;
    S=O.synthetic;
    synRows{k}=struct( ...
        'candidate',calTable.candidate(tableRow), ...
        'syntheticPassed',logical(S.passed), ...
        'affineError',S.affineError, ...
        'matrixError',S.matrixError, ...
        'mixedRelativeKIIError',S.mixedRelativeKIIError, ...
        'superpositionError',S.superpositionError, ...
        'pureILeakageRatio',S.table.recoveredKII(1)/S.table.recoveredKI(1), ...
        'pureIIRecoveredKI',S.table.recoveredKI(2), ...
        'pureIIRecoveredKII',S.table.recoveredKII(2), ...
        'mixedRecoveredKII',S.table.recoveredKII(3));
end
synTable=struct2table(vertcat(synRows{:}));
fprintf('\nPRESCRIBED-FIELD QUALIFICATION — BEST FEW ONLY\n');
disp(synTable);

passed=find(synTable.syntheticPassed);
if isempty(passed)
    R=finalize_no_selection(prefix,baselineWorst,calTable,params, ...
        'Best mesh candidates failed prescribed-field qualification.');
    R.syntheticTable=synTable;
    save_outputs(prefix,R);
    fprintf('STOP: no synthetically qualified calibration candidate.\n');
    return
end

% Winner = best mesh-only rank among synthetic-pass candidates.
winnerName=synTable.candidate(passed(1));
winnerRow=find(calTable.candidate==winnerName,1);
winnerId=sscanf(char(winnerName),'C%d');
winnerCal=params{winnerId};

fprintf('\n============================================================\n');
fprintf('SELECTED STEP62B CANDIDATE: %s\n',winnerName);
fprintf('============================================================\n');
fprintf('  L = %.3f mm; farSlope = %.6g; target ratio = %.3f\n', ...
    1e3*winnerCal.transitionLength_m,winnerCal.farSlope, ...
    winnerCal.neighborRatioTarget);
fprintf('  Regenerating ONCE with full artifacts and provenance.\n');

selectedPrefix=fullfile(vdir,'step62b_calibrated_mesh_selected');
selected=main_step62_structured_graded_mesh( ...
    'CheckpointFile',cp, ...
    'SavePrefix',selectedPrefix, ...
    'Visible',opt.Visible, ...
    'RunSynthetic',true, ...
    'ExteriorCalibration',winnerCal, ...
    'WriteArtifacts',true, ...
    'Verbose',true, ...
    'Level',0);
if ~selected.readyForOneAsymmetricFEMProposal
    error('step62b:SelectedRegenerationFailed', ...
        'Selected candidate did not reproduce its qualification.');
end

selectedWorst=neighbor_pair_table_from_file( ...
    [selectedPrefix '_candidate_T3.mat'],20);

R=struct( ...
    'baselineReproduced',baselineReproduced, ...
    'baselineWorstNeighbors',baselineWorst, ...
    'calibrationTable',calTable, ...
    'syntheticTable',synTable, ...
    'selectedCandidate',winnerName, ...
    'selectedCalibration',winnerCal, ...
    'selectedStep62',selected, ...
    'selectedWorstNeighbors',selectedWorst, ...
    'noPhysicalU',true,'noPhysicalFEM',true, ...
    'selectionRule',['structural gates -> ratio <=1.8 -> smallest ratio ', ...
        '-> lower T3 count -> prescribed-field qualification']);
save_outputs(prefix,R);

fprintf('\nSTEP62B COMPLETE — NO PHYSICAL FEM SOLVE\n');
fprintf('  Selected %s: max adjacent-size ratio %.9g\n', ...
    winnerName,selected.maxNeighborSizeRatio);
fprintf('  Exact selected candidate: %s_candidate_T3.mat\n',selectedPrefix);
end

% =========================================================================
function tf=hard_structural_pass(g)
names=fieldnames(g);
skip={'noAbruptGrading','structuralPass'};
tf=true;
for k=1:numel(names)
    if ismember(names{k},skip),continue,end
    tf=tf&&logical(g.(names{k}));
end
end

function row=failed_row(idx,Lmm,slope,cal,ME)
row=struct( ...
    'candidate',string(sprintf('C%02d',idx)), ...
    'transitionLength_mm',Lmm,'farSlope',slope, ...
    'boundaryMetricGrowth',cal.boundaryMetricGrowth, ...
    'neighborRatioTarget',cal.neighborRatioTarget, ...
    'hardStructuralPass',false,'structuralPass',false, ...
    'maxNeighborRatio',Inf,'newT3',Inf,'newT6Nodes',Inf, ...
    'patchMinAngle_deg',NaN,'exteriorMinAngle_deg',NaN, ...
    'candidateSupportInsidePaired',false,'exteriorOutsideSupport',false, ...
    'tipFanSixTriangles',false,'nativeSamplingAdequate',false, ...
    'error',string(ME.identifier+": "+ME.message));
end

function T=neighbor_pair_table_from_file(path,nKeep)
d=load(path,'candidate');
if ~isfield(d,'candidate'),error('step62b:BadSelectedMAT','No candidate.');end
T=neighbor_pair_table(d.candidate.p,d.candidate.t,d.candidate.crack, ...
    d.candidate.pairedElementIDs,d.candidate.exteriorElementIDs,nKeep);
end

function out=neighbor_pair_table(P,T,cr,patchIDs,exteriorIDs,nKeep)
tip=cr.Pmid(end,:);a0=norm(diff(cr.Pmid));e1=diff(cr.Pmid)/a0;
R=[e1(:),[-e1(2);e1(1)]];Z=(P-tip)*R;
n=size(T,1);
a=P(T(:,1),:);b=P(T(:,2),:);c=P(T(:,3),:);
L=max([vecnorm(b-c,2,2),vecnorm(a-c,2,2),vecnorm(a-b,2,2)],[],2);
E=sort([T(:,[1 2]);T(:,[2 3]);T(:,[3 1])],2);
which=repmat((1:n)',3,1);
[U,~,g]=unique(E,'rows');
cnt=accumarray(g,1);
groups=find(cnt==2);
rows=nan(numel(groups),10);
region1=strings(numel(groups),1);region2=region1;
for k=1:numel(groups)
    tri=which(g==groups(k));
    [lo,ii]=min(L(tri));[hi,jj]=max(L(tri));
    tSmall=tri(ii);tLarge=tri(jj);edge=U(groups(k),:);
    cs=mean(Z(T(tSmall,:),:),1);
    cl=mean(Z(T(tLarge,:),:),1);
    rows(k,:)=[hi/lo,tSmall,tLarge,edge(1),edge(2), ...
        1e3*lo,1e3*hi,1e3*norm(cs),1e3*norm(cl), ...
        1e3*norm(mean(Z(edge,:),1))];
    region1(k)=region_name(tSmall,patchIDs,exteriorIDs);
    region2(k)=region_name(tLarge,patchIDs,exteriorIDs);
end
[~,ord]=sort(rows(:,1),'descend');ord=ord(1:min(nKeep,numel(ord)));
rows=rows(ord,:);region1=region1(ord);region2=region2(ord);
out=array2table(rows,'VariableNames',{ ...
    'ratio','smallElementID','largeElementID','sharedNode1','sharedNode2', ...
    'smallLongest_mm','largeLongest_mm','smallCentroidRadius_mm', ...
    'largeCentroidRadius_mm','sharedEdgeMidRadius_mm'});
out.smallRegion=region1;out.largeRegion=region2;
end

function s=region_name(id,patchIDs,exteriorIDs)
if ismember(id,patchIDs),s="paired";
elseif ismember(id,exteriorIDs),s="exterior";
else,s="other";
end
end

function R=finalize_no_selection(prefix,baselineWorst,calTable,params,msg)
R=struct('baselineReproduced',true, ...
    'baselineWorstNeighbors',baselineWorst, ...
    'calibrationTable',calTable,'parameters',{params}, ...
    'syntheticTable',table(),'selectedCandidate',"", ...
    'message',msg,'noPhysicalU',true,'noPhysicalFEM',true);
save_outputs(prefix,R);
end

function save_outputs(prefix,R)
folder=fileparts(prefix);if ~isempty(folder)&&exist(folder,'dir')~=7,mkdir(folder);end
save([prefix '_small_data.mat'],'R','-v7');
writetable(R.baselineWorstNeighbors,[prefix '_baselineWorstNeighbors.csv']);
writetable(R.calibrationTable,[prefix '_calibrationTable.csv']);
if isfield(R,'syntheticTable')&&istable(R.syntheticTable)&&height(R.syntheticTable)>0
    writetable(R.syntheticTable,[prefix '_syntheticTable.csv']);
end
if isfield(R,'selectedWorstNeighbors')&&istable(R.selectedWorstNeighbors)
    writetable(R.selectedWorstNeighbors,[prefix '_selectedWorstNeighbors.csv']);
end
end

function assert_audit_branch(root)
[status,b]=system(sprintf('git -C "%s" branch --show-current',root));
assert(status==0&&strcmp(strtrim(b),'audit/step62b-mesh-calibration'), ...
    'step62b:Branch','Run Step62B only on audit/step62b-mesh-calibration.');
end

function need(s,f)
if ~isstruct(s)||~isfield(s,f)||isempty(s.(f))
    error('step62b:MissingField','Required field %s is missing.',f);
end
end
