function [P57,O57]=main_step57_reflection_paired_control(varargin)
%MAIN_STEP57_REFLECTION_PAIRED_CONTROL
% Guarded ONE-SOLVE driver for the exact Step56 reflected symmetric mesh.
%
% DEFAULT IS SAFE: AllowSolve=false. The function validates the locally
% saved Step56 candidate and refuses to create a new FEM solution unless
% the investigator explicitly passes 'AllowSolve',true.
%
% It NEVER regenerates/remeshes the Step56 candidate. The solver receives
% candidate.p/candidate.t exactly as saved by the successful mesh-only run.
% After one authorized solve, it checkpoints that field and runs only the
% already audited native-COD diagnostic. EDI remains a separate later step.
%
% Safe/default:
%   [P57,O57]=main_step57_reflection_paired_control();
%
% Only after explicit investigator authorization:
%   [P57,O57]=main_step57_reflection_paired_control('AllowSolve',true);
%
% NO EDI is performed here.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
vdir=fullfile(root,'verification');
ip=inputParser;
addParameter(ip,'AllowSolve',false,@(x)islogical(x)&&isscalar(x));
addParameter(ip,'CandidateFile', ...
    fullfile(vdir,'step56_reflected_mesh_only_candidate_T3.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'PreflightFile', ...
    fullfile(vdir,'step56_reflected_mesh_only_small_data.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'CheckpointFile', ...
    fullfile(vdir,'step57_reflection_paired_symmetric_theta0_solved.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
parse(ip,varargin{:});
opt=ip.Results;
addpath(genpath(root));
candFile=char(opt.CandidateFile);
preFile=char(opt.PreflightFile);
cp=char(opt.CheckpointFile);
if exist(candFile,'file')~=2 || exist(preFile,'file')~=2
    error('step57:MissingStep56LocalFiles', ...
        ['Run the successful Step56 mesh-only preflight locally first. ', ...
         'Both exact candidate and compact report are required.']);
end
a=load(candFile,'candidate');
b=load(preFile,'O56');
if ~isfield(a,'candidate')||~isfield(b,'O56')
    error('step57:BadStep56File','Expected candidate and O56 variables.');
end
candidate=a.candidate;
O56=b.O56;
for f={'p','t','crack','source','provenance','noFEMField'}
    require(candidate,f{1});
end
for f={'summary','gates','settings','step55Source', ...
        'refinedReferenceCheckpoint','sourceCrack','nativeR'}
    require(O56,f{1});
end
if ~candidate.noFEMField || ...
        ~O56.noNewFEM || ~O56.noEDI || ...
        ~O56.gates.meshReadyForReview || ...
        ~O56.gates.readyForOneReflectedFEMProposal
    error('step57:Step56NotEligible', ...
        'The local Step56 result did not pass every solve-proposal gate.');
end
if ~strcmp(char(candidate.source),char(O56.step55Source)) || ...
        abs(candidate.provenance.FaceFactor-O56.settings.FaceFactor)>1e-14 || ...
        abs(candidate.provenance.TipFactor-O56.settings.TipFactor)>1e-14
    error('step57:CandidateProvenanceMismatch', ...
        'Candidate T3 file and compact Step56 report differ.');
end
if size(candidate.p,2)~=2 || size(candidate.t,2)~=3 || ...
        any(~isfinite(candidate.p(:))) || ...
        any(candidate.t(:)<1) || ...
        any(candidate.t(:)>size(candidate.p,1))
    error('step57:InvalidCandidateT3','Saved Step56 T3 candidate is invalid.');
end
T=O56.summary;
if height(T)~=1 || ...
        size(candidate.p,1)~=T.assembledT3Nodes || ...
        size(candidate.t,1)~=T.assembledT3Triangles
    error('step57:CandidateCountMismatch', ...
        'Saved exact T3 candidate no longer matches Step56 counts.');
end
refCP=char(O56.refinedReferenceCheckpoint);
if exist(refCP,'file')~=2
    error('step57:ReferenceMissing', ...
        'Saved Step47 control is required to verify unchanged physics.');
end
ref=load(refCP,'mat','crack','a0','meta');
for f={'mat','crack','a0','meta'}
    require(ref,f{1});
end
if ~strcmp(ref.meta.stage,'step47_refined_control') || ...
        ~strcmp(ref.meta.caseType,'step45_centered_half_theta0') || ...
        ref.meta.Npoly~=240 || abs(ref.a0-.004)>1e-12 || ...
        norm(candidate.crack.Pmid-ref.crack.Pmid,'fro')>1e-12 || ...
        norm(candidate.crack.Pmid-O56.sourceCrack,'fro')>1e-12
    error('step57:PhysicalReferenceMismatch', ...
        'Candidate crack/physical control differs from Step47.');
end

% Recompute structural/sampling metrics directly from the SAVED candidate.
P=candidate.p;
t=candidate.t;
signedA=triangle_signed(P,t);
if any(~isfinite(signedA)) || min(signedA)<=1e-18
    error('step57:CandidateAreaFailure', ...
        'Saved reflected candidate contains non-positive T3 areas.');
end
[coord6,conn6]=T3toT6_fast(P,t);
meshTry=struct('coord3',P,'connect3',t, ...
               'coord',coord6,'connect',conn6);
if size(coord6,1)~=T.assembledT6Nodes
    error('step57:T6CountMismatch','Candidate T6 count changed.');
end
zeroU=zeros(2*size(coord6,1),1);
[r,~,face]=native_COD_audit( ...
    meshTry,zeroU,ref.mat,candidate.crack,2);
x=r/ref.a0;
fitCounts=[nnz(x>=.04&x<=.30), ...
           nnz(x>=.08&x<=.30), ...
           nnz(x>=.12&x<=.30)];
if face.nUpper~=T.upperNativeT6FaceNodes || ...
        face.nLower~=T.lowerNativeT6FaceNodes || ...
        abs(face.gridMismatch-T.faceGridMismatch_m)>1e-12 || ...
        any(fitCounts~=[T.n_004_030,T.n_008_030,T.n_012_030]) || ...
        numel(r)~=numel(O56.nativeR) || ...
        max(abs(r(:)-O56.nativeR(:)))>1e-12
    error('step57:NativeSamplingMismatch', ...
        'Saved candidate does not reproduce Step56 native crack-face sampling.');
end
tip=candidate.crack.Pmid(end,:);
tol=max(1e-12,1e-8*ref.a0);
triTip=t(any(t==candidate.crack.tipNode,2),:);
a1=P(triTip(:,1),:);a2=P(triTip(:,2),:);a3=P(triTip(:,3),:);
cent=(a1+a2+a3)/3;
nAbove=nnz(cent(:,2)>tip(2)+tol);
nBelow=nnz(cent(:,2)<tip(2)-tol);
edges=[hypot(a1(:,1)-a2(:,1),a1(:,2)-a2(:,2)); ...
       hypot(a2(:,1)-a3(:,1),a2(:,2)-a3(:,2)); ...
       hypot(a3(:,1)-a1(:,1),a3(:,2)-a1(:,2))];
edges=edges(edges>tol);
hTip=median(edges);
if nAbove~=T.tipTrianglesAbove || ...
        nBelow~=T.tipTrianglesBelow || ...
        abs(hTip-T.tipMedianEdge_m)>1e-10 || ...
        nAbove~=nBelow
    error('step57:TipFanMismatch', ...
        'Saved candidate tip fan differs from passed Step56 result.');
end
% Explicit topology at y=0: one shared intact-ligament node set ahead of
% tip; two distinct crack-face T3 node IDs behind tip, sharing tip only.
up=unique(candidate.crack.upperNodes(:));
lo=unique(candidate.crack.lowerNodes(:));
tipID=candidate.crack.tipNode;
if ~isequal(intersect(up,lo),tipID) || ...
        max(hypot(P(up,1)-P(lo,1),P(up,2)-P(lo,2)))>tol
    error('step57:CrackTopologyChanged', ...
        'Coincident upper/lower crack-face T3 nodes are not distinct as required.');
end
axisNodes=find(abs(P(:,2)-tip(2))<=tol & ...
               P(:,1)>=tip(1)-tol);
[~,~,grp]=unique(round(P(axisNodes,:)/tol)*tol,'rows');
if numel(unique(grp))~=numel(axisNodes)
    error('step57:DuplicatedIntactLigament', ...
        'Intact ligament contains duplicate coincident node IDs.');
end

fprintf('\n============================================================\n');
fprintf('STEP 57: EXACT STEP56 CANDIDATE — GUARDED SYMMETRIC CONTROL\n');
fprintf('============================================================\n');
fprintf(['  Verified saved mesh: T3=%d, T6=%d, native=%d/%d, ', ...
    'windows=%d/%d/%d.\n'],size(t,1),size(coord6,1), ...
    face.nUpper,face.nLower,fitCounts);
fprintf('  Tip fan=%d/%d; hTip=%.9g m; no mesh regeneration.\n', ...
    nAbove,nBelow,hTip);

% A previous valid checkpoint is always reused; never overwrite it.
if exist(cp,'file')==2
    old=load(cp,'meta','a0');
    if ~isfield(old,'meta') || ...
            ~strcmp(old.meta.stage,'step57_reflection_paired_control') || ...
            ~strcmp(old.meta.caseType,'step45_centered_half_theta0') || ...
            old.meta.nT3~=size(t,1) || ...
            old.meta.nT6~=size(coord6,1) || ...
            abs(old.a0-ref.a0)>1e-12 || ...
            ~strcmp(char(old.meta.candidateFile),candFile)
        error('step57:ExistingCheckpointMismatch', ...
            'Existing Step57 file is not this exact approved candidate.');
    end
    fprintf('  Reusing existing Step57 solved checkpoint; NO new solve.\n');
    P57=struct('checkpointPath',cp,'newSolve',false, ...
        'reusedFile',true,'meta',old.meta);
else
    if ~opt.AllowSolve
        error('step57:ExplicitSolveApprovalRequired', ...
            ['Step56 candidate passed every solve-proposal gate, but ', ...
             'NO FEM solve has been authorized. If the investigator ', ...
             'explicitly approves exactly one solve, rerun with ', ...
             '''AllowSolve'',true.']);
    end
    C=cfg_centered_half_domain();
    C.hole.npoly=240;
    C.holes={C.hole};
    C.a0=ref.a0;
    C.solver.verbose=0;
    if abs(C.E-ref.mat.E)>1e-10*max(1,abs(ref.mat.E)) || ...
            abs(C.nu-ref.mat.nu)>1e-12 || C.ps~=ref.mat.ps || ...
            ~strcmp(C.domain.mode,'centered_right_half') || ...
            ~strcmp(C.load.type,'remote_tension_y') || ...
            ~strcmp(C.bc.anchor_mode,'symmetry_half_x')
        error('step57:PhysicalSetupChanged', ...
            'Current control configuration differs from Step47.');
    end
    G=struct('p',candidate.p,'t',candidate.t);
    fprintf('  Starting exactly ONE explicitly authorized FEM solve.\n');
    S2=solve_cracked_LEFM(C,G,'lambda',1.0);
    if ~isfield(S2,'mesh')||~isfield(S2,'U')|| ...
            size(S2.mesh.coord3,1)~=size(P,1) || ...
            size(S2.mesh.connect3,1)~=size(t,1) || ...
            size(S2.mesh.coord,1)~=size(coord6,1) || ...
            numel(S2.U)~=2*size(coord6,1) || ...
            any(~isfinite(S2.U))
        error('step57:InvalidSolvedField', ...
            'Authorized solver did not return the exact candidate size.');
    end
    if ~isequal(S2.mesh.connect3,t) || ...
            max(abs(S2.mesh.coord3(:)-P(:)))>1e-12 || ...
            ~isequal(S2.mesh.connect,conn6) || ...
            max(abs(S2.mesh.coord(:)-coord6(:)))>1e-12
        error('step57:SolvedMeshMismatch', ...
            'Solver did not operate on exact saved Step56 T3/T6 candidate.');
    end
    mesh=S2.mesh;
    U=S2.U;
    mat=S2.mat;
    crack=candidate.crack;
    a0=ref.a0;
    meta=struct('caseType','step45_centered_half_theta0', ...
        'stage','step57_reflection_paired_control', ...
        'source','one explicitly authorized reflection-paired symmetric FEM solve', ...
        'Npoly',240,'a0',a0,'zeroAngleDeg',0, ...
        'nT3',size(mesh.connect3,1),'nT6',size(mesh.coord,1), ...
        'hTipSelected',hTip,'nativeRSelected',r(:), ...
        'candidateFile',candFile,'preflightFile',preFile, ...
        'referenceStep47Checkpoint',refCP, ...
        'symmetryExpectation','KII=0 in symmetric continuum', ...
        'exactMeshReused',true, ...
        'EDIperformed',false);
    [folder,~,~]=fileparts(cp);
    if ~isempty(folder)&&exist(folder,'dir')~=7,mkdir(folder);end
    tmp=[cp '.incomplete.mat'];
    if exist(tmp,'file')==2
        error('step57:InterruptedSave', ...
            'Inspect/remove prior incomplete checkpoint manually: %s',tmp);
    end
    save(tmp,'mesh','U','mat','crack','a0','meta','-v7.3');
    [ok,msg]=movefile(tmp,cp);
    if ~ok,error('step57:CheckpointSaveFailed','%s',msg);end
    fprintf('  Saved unique solved checkpoint: %s\n',cp);
    P57=struct('checkpointPath',cp,'newSolve',true, ...
        'reusedFile',false,'meta',meta);
    clear S2 mesh U mat C G
end

% COD-only postprocessing is inexpensive and was predeclared. No EDI.
fprintf('STEP 57: native COD ONLY on the saved reflection-paired field.\n');
O57=main_step45_symmetric_field_leakage(P57, ...
    'RunEDI',false, ...
    'SavePrefix',fullfile(vdir, ...
        'step57_reflection_paired_symmetric_field_leakage'));
disp(O57.fitTable);
disp(O57.CODgates);
fprintf('  EDI was NOT run. Stop after COD and inspect the result.\n');
end

function A=triangle_signed(P,T)
a=P(T(:,1),:);b=P(T(:,2),:);c=P(T(:,3),:);
A=.5*((b(:,1)-a(:,1)).*(c(:,2)-a(:,2))- ...
      (c(:,1)-a(:,1)).*(b(:,2)-a(:,2)));
end

function require(s,f)
if ~isstruct(s)||~isfield(s,f)||isempty(s.(f))
    error('step57:MissingField','Missing required field %s.',f);
end
end
