function R48=main_step48_refined_matched_edi(varargin)
%MAIN_STEP48_REFINED_MATCHED_EDI  ONE matched 16-point EDI, NO FEM SOLVE.
%
% Step 47 gave an actual refined symmetric FEM field, with fully populated
% but window/degree-sensitive native COD extrapolations. Step 48 evaluates
% only ONE EDI annulus on this PREVIOUSLY SAVED field, holding precisely
% the same PHYSICAL r_inner and r_outer as Step 45 coarse EDI at 0.65*a0.
% It never substitutes 2*hTip of the refined mesh for the baseline inner
% radius. The Step-45 postprocessor handles the one EDI integration and
% a per-domain progress cache, with unchanged 16-point FE-nodal method.
%
% No FEM solve, no mesh generation, no new physical boundary problem.
% The EDI calculation may be costly, but is performed at one domain only.
%
% After pulling the audit branch:
%   addpath(genpath(pwd));
%   R48=main_step48_refined_matched_edi();
%   disp(R48.comparison);
%
% Defaults assume the local files created by the investigator's
% already-completed Steps 45 and 47 under <repo>/verification.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
verDir=fullfile(root,'verification');
ip=inputParser;
addParameter(ip,'OriginalResultsFile', ...
    fullfile(verDir,'step45_symmetric_field_leakage_small_data.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'RefinedCheckpoint', ...
    fullfile(verDir,'step47_refined_symmetric_theta0_solved.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'SavePrefix', ...
    fullfile(verDir,'step48_refined_matched_edi'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
parse(ip,varargin{:});
opt=ip.Results;
addpath(genpath(root));
oldFile=char(opt.OriginalResultsFile);
refinedCP=char(opt.RefinedCheckpoint);
prefix=char(opt.SavePrefix);
if exist(oldFile,'file')~=2
    error('step48:MissingBaselineEDI', ...
        'Original Step45 three-domain compact EDI file is absent: %s',oldFile);
end
if exist(refinedCP,'file')~=2
    error('step48:MissingRefinedCheckpoint', ...
        'The approved Step47 refined FEM solution is absent: %s',refinedCP);
end
B=load(oldFile,'O45');
if ~isfield(B,'O45')
    error('step48:BadBaselineFile', ...
        'Expected saved variable O45 in baseline compact file.');
end
base=B.O45;
if ~isfield(base,'EDI') || ~isfield(base.EDI,'performed') || ...
        ~base.EDI.performed || ~isfield(base.EDI,'table') || ...
        ~istable(base.EDI.table) || ...
        ~all(ismember({'r_outer_over_a0','r_inner','KI','KII','ratio'}, ...
                       base.EDI.table.Properties.VariableNames))
    error('step48:BaselineEDIUnverified', ...
        'Baseline O45 must contain completed 16-point EDI results.');
end
ref=load(refinedCP,'meta','a0');
if ~isfield(ref,'meta') || ~isfield(ref,'a0')
    error('step48:UnrecognizedRefinedCheckpoint', ...
        'Refined solution lacks provenance metadata.');
end
m=ref.meta;
if ~isfield(m,'stage') || ...
        ~strcmp(m.stage,'step47_refined_control') || ...
        ~strcmp(m.caseType,'step45_centered_half_theta0') || ...
        m.Npoly~=240 || abs(m.a0-0.004)>1e-12 || ...
        m.nT6~=5054 || m.nT3~=2391 || ...
        abs(m.faceFactor-0.125)>1e-12 || ...
        abs(m.tipFactor-0.5)>1e-12 || ...
        abs(ref.a0-base.meta.a0)>1e-12 || ...
        ~strcmpi(char(m.baselineCheckpoint),char(base.checkpointPath))
    error('step48:UnmatchedPhysicalControl', ...
        'Refined checkpoint is not the selected same-geometry Step47 field.');
end
ratio=0.65;
i=find(abs(base.EDI.table.r_outer_over_a0-ratio)<1e-12);
if numel(i)~=1
    error('step48:AbsentReferenceDomain', ...
        'Original O45 EDI table must contain exactly one 0.65*a0 domain.');
end
ri=base.EDI.table.r_inner(i);
ro=ratio*ref.a0;
if ~all(isfinite([ri,ro,base.EDI.table.KI(i), ...
                         base.EDI.table.KII(i)])) || ...
        base.EDI.table.KI(i)<=0 || ...
        ri<2*m.hTipSelected || ri>=ro || ...
        abs(base.EDI.table.ratio(i)- ...
            base.EDI.table.KII(i)/base.EDI.table.KI(i))>1e-12
    error('step48:UnmatchedDomain', ...
        'Original absolute EDI domain and selected refined tip are incompatible.');
end
fprintf('\n============================================================\n');
fprintf('STEP 48: ONE ACTUAL-FEM MATCHED EDI ON REFINED SYMMETRIC FIELD\n');
fprintf('============================================================\n');
fprintf('  Refined mesh: %d T6 nodes, %d T3 triangles.\n', ...
    m.nT6,m.nT3);
fprintf('  EXACT matched r_inner = %.12g m, r_outer = %.12g m.\n',ri,ro);
fprintf('  Baseline signed KII/KI at same annulus: %+.10e.\n', ...
    base.EDI.table.ratio(i));
fprintf('  NO mesh, FEM solve, or extra EDI domains requested.\n');

% The previously audited Step45 postprocessor accepts both stages under
% the same physical caseType, and always performs native COD first.
% Preserve its 16-point FE-nodal settings and per-domain progress cache.
O=main_step45_symmetric_field_leakage(refinedCP, ...
    'RunEDI',true, ...
    'ROuterOverA0',ratio, ...
    'InnerRadius',ri, ...
    'SavePrefix',prefix);
if ~O.EDI.performed || height(O.EDI.table)~=1 || ...
        abs(O.EDI.table.r_inner-ri)>1e-12 || ...
        abs(O.EDI.table.r_outer_over_a0-ratio)>1e-12
    error('step48:EDIResultMismatch', ...
        'Refined EDI must evaluate only the matching baseline annulus.');
end
oldKI=base.EDI.table.KI(i);oldKII=base.EDI.table.KII(i);
newKI=O.EDI.table.KI(1);newKII=O.EDI.table.KII(1);
q0=oldKII/oldKI;
q1=newKII/newKI;
T=table([{'Original Step45'};{'Refined Step47'}], ...
    [oldKI;newKI],[oldKII;newKII],[q0;q1], ...
    repmat(ri,2,1),repmat(ro,2,1), ...
    'VariableNames',{'field','KI','KII','ratio','r_inner','r_outer'});
fprintf('\nMATCHED SAME-GEOMETRY SYMMETRIC-FEM EDI RESULTS\n');
disp(T);
fprintf('  signed delta(refined - original) ratio = %+.10e\n',q1-q0);
fprintf(['  These numerical residuals are NOT uncertainty bounds ', ...
    'for the fine asymmetric crack problem.\n']);
R48=struct('comparison',T,'refined',O, ...
    'baselineSource',oldFile, ...
    'matchedInner',ri,'matchedOuter',ro, ...
    'signedRatioChange',q1-q0,'noNewFEM',true);
save([prefix '_comparison_small_data.mat'],'R48');
fprintf('  Cached compact Step48 matched comparison; NO FEM solve.\n');
end