function R59=main_step59_paired_exact_pureI_nodal(varargin)
%MAIN_STEP59_PAIRED_EXACT_PUREI_NODAL
% Prescribed exact leading Williams KI=1,KII=0 sampled at the NODES of
% the already solved, exactly reflection-paired Step57 T6 mesh.
%
% ONE no-solve, no-remesh 16-point FE-nodal-q EDI calculation on the
% exact Step58 matched annulus. This tests whether the synthetic nodal
% interpolation leakage previously measured on unpaired symmetric meshes
% also collapses when the T3/T6 topology is exactly reflection-paired.
%
% No FEM solve, no mesh generation, no physical field modification.
%
% Usage:
%   addpath(genpath(pwd));
%   R59=main_step59_paired_exact_pureI_nodal();
%   disp(R59.table);
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
vdir=fullfile(root,'verification');
ip=inputParser;
addParameter(ip,'Step58EDIFile', ...
    fullfile(vdir,'step58_reflection_paired_matched_edi_small_data.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'SavePrefix', ...
    fullfile(vdir,'step59_paired_exact_pureI_nodal'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
parse(ip,varargin{:});
opt=ip.Results;
addpath(genpath(root));

src=char(opt.Step58EDIFile);
prefix=char(opt.SavePrefix);
if exist(src,'file')~=2
    error('step59:MissingStep58EDI', ...
        'Missing completed Step58 O45 EDI file: %s',src);
end
d=load(src,'O45');
if ~isfield(d,'O45')
    error('step59:BadStep58File','Expected saved O45 from Step58.');
end
O45=d.O45;
for f={'checkpointPath','meta','EDI','CODgates','faceGridMismatch'}
    need(O45,f{1});
end
if ~strcmp(O45.meta.caseType,'step45_centered_half_theta0') || ...
        ~strcmp(O45.meta.stage,'step57_reflection_paired_control') || ...
        O45.meta.Npoly~=240 || O45.meta.nT3~=2578 || ...
        O45.meta.nT6~=5427 || ...
        ~isfield(O45.meta,'exactMeshReused') || ...
        ~O45.meta.exactMeshReused || ...
        ~O45.EDI.performed || ...
        ~istable(O45.EDI.table) || height(O45.EDI.table)~=1 || ...
        abs(O45.EDI.table.r_outer_over_a0(1)-0.65)>1e-12 || ...
        O45.faceGridMismatch>1e-12 || ...
        ~O45.CODgates.evaluated || ~O45.CODgates.passed || ...
        O45.CODgates.maxAbsRatio>1e-10
    error('step59:WrongPairedControl', ...
        'Step58 source is not the verified paired Step57 symmetric field.');
end
if abs(O45.EDI.table.ratio(1))>1e-10
    error('step59:Step58EDINotRoundoff', ...
        'Expected paired actual-FEM EDI symmetry residual near roundoff.');
end
ri=O45.EDI.table.r_inner(1);
if abs(ri-0.00086750243077)>1e-12
    error('step59:UnexpectedAnnulus', ...
        'Step59 is restricted to the exact historical matched inner radius.');
end

fprintf('\n============================================================\n');
fprintf('STEP 59: EXACT NODAL PURE-I ON REFLECTION-PAIRED STEP57 T6\n');
fprintf('============================================================\n');
fprintf('  Source actual FEM EDI q = %+.10e.\n',O45.EDI.table.ratio(1));
fprintf('  Same annulus: r_inner=%.12g m, r_outer=%.12g m.\n', ...
    ri,0.65*O45.meta.a0);
fprintf('  Prescribed exact KI=1,KII=0 sampled at T6 nodes.\n');
fprintf('  NO FEM solve, mesh, remesh or radius sweep.\n');

Out=main_step45_coarse_exact_pureI_replay(O45, ...
    'ROuterOverA0',0.65, ...
    'SavePrefix',prefix);
if ~isfield(Out,'table') || ~istable(Out.table) || ...
        height(Out.table)~=1
    error('step59:UnexpectedReplayOutput', ...
        'Expected exactly one exact-nodal replay row.');
end
T=Out.table;
if abs(T.r_outer_over_a0(1)-0.65)>1e-12 || ...
        abs(T.r_inner(1)-ri)>1e-12 || ...
        abs(T.actual_ratio(1)-O45.EDI.table.ratio(1))>1e-12 || ...
        ~all(isfinite([T.exact_KI(1),T.exact_KII_leakage(1), ...
                       T.exact_ratio_leakage(1)])) || ...
        T.exact_KI(1)<=0
    error('step59:ReplayMismatch', ...
        'Exact nodal replay did not use the Step58 matched field/domain.');
end
if Out.CODSelfCheck.maxAbsKIError>1e-8 || ...
        Out.CODSelfCheck.maxAbsKIILeakage>1e-8
    error('step59:ExactCODSelfCheck', ...
        'Prescribed pure-I nodal field failed exact crack-face COD check.');
end

fprintf('\nPAIRED-MESH ACTUAL FEM vs PRESCRIBED EXACT-NODAL PURE-I\n');
disp(T);
fprintf('  exact-nodal |q| = %.10e\n',abs(T.exact_ratio_leakage(1)));
fprintf('  actual-FEM  |q| = %.10e\n',abs(T.actual_ratio(1)));
fprintf(['  This is a prescribed-field interpolation control, NOT an ', ...
    'error correction for an asymmetric physical KII.\n']);

R59=struct('table',T, ...
    'sourceStep58File',src, ...
    'replay',Out, ...
    'pairedActualRatio',T.actual_ratio(1), ...
    'pairedExactNodalRatio',T.exact_ratio_leakage(1), ...
    'noNewFEM',true,'noMesh',true,'singleEDIDomain',true, ...
    'interpretation',['Known pure-I nodal interpolation control on ', ...
      'exactly reflection-paired T6 topology.']);
save([prefix '_comparison_small_data.mat'],'R59');
fprintf('  Compact Step59 comparison saved. No FEM solve occurred.\n');
end

function need(s,f)
if ~isstruct(s)||~isfield(s,f)||isempty(s.(f))
    error('step59:MissingField','Required field %s is missing.',f);
end
end
