function O56=main_step56_reflected_mesh_preflight(varargin)
%MAIN_STEP56_REFLECTED_MESH_PREFLIGHT
% Step 56: MESH-ONLY, never calls a FEM solver or EDI.
% Triangulate the exact Step55 upper source polygon ONCE with PDE Toolbox;
% mirror that SAME upper T3 triangulation to make the bottom mesh.
% SHARE axis nodes on the intact tip->right-plate ligament; DUPLICATE
% upper/lower pencil-face nodes behind the tip except for the common tip.
% Collapse only these original pencil-face nodes to the unchanged crack.
% Verify topology, mirrored elements, positive collapsed element areas,
% actual native COD sampling and source exterior-vertex preservation.
% Save the exact candidate p,t,crack ONLY if all structural gates pass.
%
% The new candidate will have DIFFERENT connectivity from prior Step47:
% same prescribed polygon and physical setup does not imply a matched-
% exterior triangulation or convergence of an actual physical SIF.
%
% After pulling audit:
%   addpath(genpath(pwd));
%   O56=main_step56_reflected_mesh_preflight();
%   disp(O56.summary); disp(O56.gates);
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
vdir=fullfile(root,'verification');
ip=inputParser;
addParameter(ip,'Step55File', ...
    fullfile(vdir,'step55_upper_half_boundary_small_data.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'ReferenceCheckpoint', ...
    fullfile(vdir,'step47_refined_symmetric_theta0_solved.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'FaceFactor',0.125, ...
    @(x)isnumeric(x)&&isscalar(x)&&isfinite(x)&&x>0&&x<1);
addParameter(ip,'TipFactor',0.5, ...
    @(x)isnumeric(x)&&isscalar(x)&&isfinite(x)&&x>0&&x<1);
addParameter(ip,'Tolerance_m',1e-10, ...
    @(x)isnumeric(x)&&isscalar(x)&&isfinite(x)&&x>0);
addParameter(ip,'SavePrefix', ...
    fullfile(vdir,'step56_reflected_mesh_only'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
parse(ip,varargin{:});
opt=ip.Results;
addpath(genpath(root));
source=char(opt.Step55File);
if exist(source,'file')~=2
    error('step56:Step55Missing', ...
        'The locally executed, passed Step55 polygon report is required.');
end
f=load(source,'O55');
if ~isfield(f,'O55')|| ...
        ~isfield(f.O55,'summary')|| ...
        ~isfield(f.O55,'upperHalfPolygon')|| ...
        ~isfield(f.O55,'sourceCrack')
    error('step56:Step55BadFile','Step55 report has incomplete provenance.');
end
s=f.O55;
if height(s.summary)~=1 || ...
        ~logical(s.summary.upperSplitAndReconstructionPass(1)) || ...
        s.summary.nUpperPolygonVertices(1)~=65 || ...
        s.summary.unmatchedExteriorEdges(1)~=0 || ...
        s.summary.maxExteriorEdgeReconstructionError_m(1)>1e-12
    error('step56:UnapprovedBoundary', ...
        'Only the verified Step55 65-vertex upper polygon is accepted.');
end
refCP=char(opt.ReferenceCheckpoint);
if exist(refCP,'file')~=2
    error('step56:ReferenceAbsent','Previously solved Step47 checkpoint missing.');
end
reference=load(refCP,'crack','a0','mat','meta');
if ~isfield(reference,'meta') || ...
        ~strcmp(reference.meta.stage,'step47_refined_control') || ...
        ~strcmp(reference.meta.caseType,'step45_centered_half_theta0') || ...
        reference.meta.Npoly~=240 || ...
        abs(reference.a0-0.004)>1e-12 || ...
        norm(reference.crack.Pmid-s.sourceCrack,'fro')>1e-12
    error('step56:ReferenceChanged', ...
        'Selected Step47 checkpoint and Step55 polygon do not match.');
end
C=cfg_centered_half_domain();
C.hole.npoly=240;
C.holes={C.hole};
C.a0=reference.a0;
hArc=2*pi*C.hole.r/C.hole.npoly;
if abs(C.E-reference.mat.E)>1e-10 || ...
        abs(C.nu-reference.mat.nu)>1e-12 || ...
        C.ps~=reference.mat.ps || ...
        ~strcmp(C.domain.mode,'centered_right_half') || ...
        ~strcmp(C.bc.anchor_mode,'symmetry_half_x') || ...
        ~strcmp(C.load.type,'remote_tension_y')
    error('step56:PhysicalSetupChanged', ...
        'Configuration/material differs from saved symmetric control.');
end
D=build_domain_centered_half_pencil(s.sourceCrack,C,C.mesh2.chw);
Q=s.upperHalfPolygon;
if norm(D.outerPoly-s.originalOuterPolygon,'fro')>1e-12 || ...
        norm(D.channelGeom.append.face_upper- ...
             s.originalUpperPencilFace,'fro')>1e-12 || ...
        abs(s.artificialSeam(2,1)-C.A)>1e-12 || ...
        norm(s.artificialSeam(1,:)-D.Pmid(end,:))>1e-12
    error('step56:SourcePolygonChanged', ...
        'Refuse any implicit change to the prescribed source polygon.');
end
tol=opt.Tolerance_m;
pTip=s.sourceCrack(end,:);
pMouthUpper=s.originalUpperPencilFace(1,:);
pRight=[C.A,pTip(2)];

fprintf('\n============================================================\n');
fprintf('STEP 56: UPPER T3 -> EXACTLY REFLECTED T3, MESH ONLY\n');
fprintf('============================================================\n');
fprintf('  Source Step55 upper polygon: %d original vertices.\n',size(Q,1));
fprintf('  NO FEM, stiffness, EDI or physical displacement field.\n');

% Create only the upper polygonal geometry; original vertices are unchanged.
nq=size(Q,1);
gd=[2;nq;Q(:,1);Q(:,2)];
[dl,~]=decsg(gd,'R1',char('R1').');
mdl=createpde();
geometryFromEdges(mdl,dl);
seed=generateMesh(mdl,'GeometricOrder','linear', ...
    'Hmin',hArc,'Hmax',20*hArc,'Hgrad',C.mesh1.hgrad);
geom=mdl.Geometry;
numEdges=geom.NumEdges;
numVertices=geom.NumVertices;
faceEdges=[];
seamEdges=[];
for e=1:numEdges
    ii=unique(findNodes(seed,'region','Edge',e));
    p=seed.Nodes(:,ii).';
    if size(p,1)<2,continue;end
    if whole_edge_is_segment(p,pMouthUpper,pTip,tol)
        faceEdges(end+1)=e; %#ok<AGROW>
    end
    if whole_edge_is_segment(p,pTip,pRight,tol)
        seamEdges(end+1)=e; %#ok<AGROW>
    end
end
tipVertices=[];
for v=1:numVertices
    ii=unique(findNodes(seed,'region','Vertex',v));
    if isempty(ii),continue;end
    p=seed.Nodes(:,ii).';
    if size(p,1)==1 && norm(p-pTip)<tol
        tipVertices(end+1)=v; %#ok<AGROW>
    end
end
if numel(faceEdges)~=1 ||numel(seamEdges)~=1 || ...
        faceEdges==seamEdges ||numel(tipVertices)~=1
    error('step56:AmbiguousUpperPDEEdges', ...
        ['Cannot uniquely identify upper pencil edge, artificial ', ...
         'intact-ligament edge and tip vertex on upper PDE geometry.']);
end
eFace=faceEdges(1);
eSeam=seamEdges(1);
vTip=tipVertices(1);
faceSize=opt.FaceFactor*hArc;
tipSize=opt.TipFactor*.5*hArc;
fprintf('  Upper PDE IDs: face edge %d; seam edge %d; tip vertex %d.\n', ...
    eFace,eSeam,vTip);
fprintf('  Requested local face %.9g m, tip %.9g m.\n',faceSize,tipSize);

% Only ONE final upper mesh: mirroring does not invoke a second mesher.
upper=generateMesh(mdl,'GeometricOrder','linear', ...
    'Hmin',hArc,'Hmax',20*hArc,'Hgrad',C.mesh1.hgrad, ...
    'Hedge',{eFace,faceSize},'Hvertex',{vTip,tipSize});
pU=upper.Nodes.';
tU=upper.Elements.';
if size(tU,2)~=3 || isempty(tU)|| any(~isfinite(pU(:)))
    error('step56:UpperMeshInvalid','Expected finite linear upper T3 mesh.');
end
% PDE mesher must retain all 65 original polygon vertex coordinates.
vDist=zeros(nq,1);
for i=1:nq
    vDist(i)=min(hypot(pU(:,1)-Q(i,1),pU(:,2)-Q(i,2)));
end
if max(vDist)>tol
    error('step56:OriginalVerticesNotRetained', ...
        'Upper mesh lost or moved one of the original boundary vertices.');
end
upperFace=unique(findNodes(upper,'region','Edge',eFace));
seam=unique(findNodes(upper,'region','Edge',eSeam));
tipNode=unique(findNodes(upper,'region','Vertex',vTip));
if numel(tipNode)~=1 || ...
        nnz(upperFace==tipNode)~=1 || ...
        nnz(seam==tipNode)~=1 || ...
        numel(intersect(upperFace,seam))~=1 || ...
        numel(upperFace)<3 || numel(seam)<3
    error('step56:TipAndBoundaryTopology', ...
        'Face and seam must have exactly ONE common node: the sharp tip.');
end
y0=pTip(2);
onAxis=find(abs(pU(:,2)-y0)<=tol);
if ~isequal(sort(onAxis(:)),sort(seam(:))) || ...
        any(pU(seam,1)<pTip(1)-tol) || ...
        any(pU(seam,1)>C.A+tol)
    error('step56:UnsharedAxisNode', ...
        'All and ONLY original tip-to-right axis nodes must form the seam.');
end
if max(abs(pU(:,2)-y0))<tol || ...
        any(pU(:,2)<y0-tol) || ...
        max(abs(pU(tipNode,:)-pTip))>tol
    error('step56:UpperMeshOutsideDomain', ...
        'Upper triangulation or actual tip coordinate is incorrect.');
end

% Normalize upper T3 triangles CCW before reflecting them, retaining each
% index. Upper mesher orientation may be implementation dependent.
upSigned=triangle_signed(pU,tU);
if any(abs(upSigned)<1e-18)
    error('step56:UpperDegenerate','Upper T3 contains a degenerate triangle.');
end
flipUp=upSigned<0;
tU(flipUp,[2 3])=tU(flipUp,[3 2]);
nU=size(pU,1);
lowerMap=(1:nU).';
nonAxis=setdiff((1:nU).',seam(:));
lowerMap(nonAxis)=nU+(1:numel(nonAxis)).';
pUncollapsed=[pU;mirror(pU(nonAxis,:),y0)];
tLower=lowerMap(tU(:,[1 3 2]));
t=[tU;tLower];
if ~all(triangle_signed(pUncollapsed,t)>1e-18)
    error('step56:MirroringInvalid', ...
        'Upper/lower T3 triangle orientation failed before collapse.');
end
% EXACT reflection by construction, including T3 element pairing.
err=max(hypot(pUncollapsed(lowerMap,1)-pU(:,1), ...
    pUncollapsed(lowerMap,2)-(2*y0-pU(:,2))));
if err>tol || size(tLower,1)~=size(tU,1)
    error('step56:ReflectionConstruction', ...
        'Every generated upper node/triangle must have one mirror counterpart.');
end

% Behind tip: TWO independent crack faces, with just the ONE shared tip.
upperFace=upperFace(:);
lowerFace=lowerMap(upperFace);
if ~isequal(intersect(upperFace,lowerFace),tipNode) || ...
        numel(unique(lowerFace))~=numel(upperFace)
    error('step56:CrackFaceIdentification', ...
        'Crack faces must be duplicated behind the one shared tip node.');
end
% Ahead of tip: the ONE shared seam, including both endpoints. Confirm
% every consecutive seam edge has exactly one upper + one lower triangle.
[~,sortSeam]=sort(pU(seam,1));
seam=seam(sortSeam);
if seam(1)~=tipNode || ...
        norm(pU(seam(end),:)-pRight)>tol
    error('step56:SeamEndpoints','Intact-ligament seam must join tip to right edge.');
end
E=[t(:,[1 2]);t(:,[2 3]);t(:,[3 1])];
E=sort(E,2);
nTup=size(tU,1);
elemIDs=repmat((1:size(t,1)).',3,1);
seamEdgeCount=zeros(numel(seam)-1,1);
sharedMidSideTest=true;
for j=1:numel(seam)-1
    test=sort(seam(j:j+1));
    matched=all(E==test(:).',2);
    seamEdgeCount(j)=nnz(matched);
    which=elemIDs(matched);
    if numel(which)~=2 || ...
            ~any(which<=nTup) || ~any(which>nTup)
        sharedMidSideTest=false;
    end
end
if ~all(seamEdgeCount==2)||~sharedMidSideTest
    error('step56:UnsharedLigament', ...
        'Each seam T3 edge must be shared by one upper and one lower T3.');
end

% COLLAPSE the original triangular pencil faces to the exact same straight
% crack. Use existing project's normalized projection on the original
% horizontal crack: x before mouth -> mouth, tip -> tip.
p=pUncollapsed;
faceS=(pU(upperFace,1)-s.sourceCrack(1,1))/reference.a0;
faceS=max(0,min(1,faceS));
target=[s.sourceCrack(1,1)+reference.a0*faceS, ...
        y0+zeros(size(faceS))];
p(upperFace,:)=target;
p(lowerFace,:)=target;
p(tipNode,:)=pTip;
if max(hypot(p(upperFace,1)-p(lowerFace,1), ...
             p(upperFace,2)-p(lowerFace,2)))>tol || ...
        numel(unique(upperFace))~=numel(upperFace) || ...
        numel(intersect(upperFace,lowerFace))~=1
    error('step56:CollapseCrackFaceMismatch', ...
        'The two coincident crack faces must keep distinct node IDs.');
end
signedAfter=triangle_signed(p,t);
areas=abs(signedAfter);
nondegenerate=all(isfinite(areas)) && min(areas)>1e-18 && ...
              all(signedAfter>0);
% Strong reflection check AFTER pencil-face projection.
postErr=max(hypot(p(lowerMap,1)-p(1:nU,1), ...
    p(lowerMap,2)-(2*y0-p(1:nU,2))));
if postErr>tol
    error('step56:CollapsedMirrorError', ...
        'The collapsed crack geometry is not exactly reflection-paired.');
end

% Upgrade the full assembled, SHARED/SEPARATED T3 topology to T6 ONCE.
[coord,connect]=T3toT6_fast(p,t);
% Each mirrored upper T6 ELEMENT must have a reflected partner, not just
% a reflected T3 triangle or a matching number of mid-side nodes.
up6=connect(1:nTup,:);
lo6=connect(nTup+1:end,:);
mirrorCols=[1 3 2 6 5 4];
t6Err=0;
for col=1:6
    from=coord(up6(:,col),:);
    to=coord(lo6(:,mirrorCols(col)),:);
    t6Err=max(t6Err,max(hypot(from(:,1)-to(:,1), ...
                               from(:,2)+to(:,2)-2*y0)));
end
if t6Err>tol
    error('step56:T6MirrorMismatch', ...
        'Complete six-node upper/lower elements do not reflect exactly.');
end
% T3toT6_fast uses a single global undirected-edge map. Confirm explicitly
% that every intact seam has ONE shared T6 midside, whereas each pair of
% coincident physical crack faces has TWO distinct T6 midsides.
t6Edges=sort([connect(:,[1 2]); ...
              connect(:,[2 3]); ...
              connect(:,[3 1])],2);
t6Mids=[connect(:,4);connect(:,5);connect(:,6)];
seamMidShared=true;
for j=1:numel(seam)-1
    targetEdge=sort(seam(j:j+1)).';
    entries=all(t6Edges==targetEdge,2);
    seamMidShared=seamMidShared && ...
        nnz(entries)==2 && numel(unique(t6Mids(entries)))==1;
end
[~,sortFace]=sort(p(upperFace,1));
sortedFace=upperFace(sortFace);
lowerSorted=lowerMap(sortedFace);
faceMidDistinct=true;
for j=1:numel(sortedFace)-1
    edgeUp=sort(sortedFace(j:j+1)).';
    edgeLow=sort(lowerSorted(j:j+1)).';
    iU=all(t6Edges==edgeUp,2);
    iL=all(t6Edges==edgeLow,2);
    faceMidDistinct=faceMidDistinct && ...
        nnz(iU)==1 && nnz(iL)==1 && ...
        t6Mids(iU)~=t6Mids(iL);
end
if ~seamMidShared || ~faceMidDistinct
    error('step56:IncorrectT6InterfaceTopology', ...
        'T6 seam midsides must be shared and crack-face midsides distinct.');
end
mesh=struct('coord3',p,'connect3',t,'coord',coord,'connect',connect);
crack=struct('Pmid',s.sourceCrack, ...
    'tipNode',tipNode,'upperNodes',upperFace, ...
    'lowerNodes',lowerFace, ...
    'x0',s.sourceCrack(1,:), ...
    'xtip',pTip,'nUpper',numel(upperFace), ...
    'nLower',numel(lowerFace));
% Native COD on ZERO DISPLACEMENT is solely an observed geometrical
% sampling/count diagnostic, NOT an FEM field or physical COD extraction.
[r,~,face]=native_COD_audit(mesh, ...
    zeros(2*size(coord,1),1),reference.mat,crack,2);
x=r/reference.a0;
fitCounts=[nnz(x>=.04&x<=.30), ...
           nnz(x>=.08&x<=.30), ...
           nnz(x>=.12&x<=.30)];
triTip=t(any(t==tipNode,2),:);
vertices=p(triTip(:,1),:);
vertices2=p(triTip(:,2),:);
vertices3=p(triTip(:,3),:);
centers=(vertices+vertices2+vertices3)/3;
nAbove=nnz(centers(:,2)>y0+tol);
nBelow=nnz(centers(:,2)<y0-tol);
L=[hypot(vertices(:,1)-vertices2(:,1), ...
         vertices(:,2)-vertices2(:,2)); ...
   hypot(vertices2(:,1)-vertices3(:,1), ...
         vertices2(:,2)-vertices3(:,2)); ...
   hypot(vertices3(:,1)-vertices(:,1), ...
         vertices3(:,2)-vertices(:,2))];
hTip=median(L(L>tol));
minAngle=minimum_angle(p,t);
gates=struct( ...
    'originalUpperBoundaryVerticesRetained',max(vDist)<=tol, ...
    'allUpperAndLowerTrianglesMirrored',err<=tol && postErr<=tol, ...
    'intactLigamentShared',all(seamEdgeCount==2), ...
    'crackFacesDistinct',numel(intersect(upperFace,lowerFace))==1, ...
    'seamT6MidsidesShared',seamMidShared, ...
    'crackT6MidsidesDistinct',faceMidDistinct, ...
    'allT6TrianglesMirrored',t6Err<=tol, ...
    'collapsedTriangleAreasPositive',nondegenerate, ...
    'tipFanSymmetric',nAbove==nBelow, ...
    'nativeFaceCoordinatesPaired',face.gridMismatch<=tol, ...
    'allThreeLinearCODWindows',all(fitCounts>=8), ...
    'allThreeQuadraticCODWindows',all(fitCounts>=12), ...
    'tipImprovedVsOriginalStep45', ...
         isfinite(hTip) && hTip<0.00043375122, ...
    'meshReadyForReview',false, ...
    'readyForOneReflectedFEMProposal',false);
gates.meshReadyForReview= ...
    gates.originalUpperBoundaryVerticesRetained && ...
    gates.allUpperAndLowerTrianglesMirrored && ...
    gates.intactLigamentShared && gates.crackFacesDistinct && ...
    gates.seamT6MidsidesShared && gates.crackT6MidsidesDistinct && ...
    gates.allT6TrianglesMirrored && ...
    gates.collapsedTriangleAreasPositive && ...
    gates.tipFanSymmetric && gates.nativeFaceCoordinatesPaired;
% A proposal gate is ONLY a structural/sampling readiness indicator.
% It never authorizes a solve; inspect achieved quality separately.
gates.readyForOneReflectedFEMProposal= ...
    gates.meshReadyForReview && ...
    gates.allThreeQuadraticCODWindows && ...
    gates.tipImprovedVsOriginalStep45;
summary=table(size(Q,1),size(pU,1),size(p,1),size(t,1), ...
    size(coord,1),numel(seam),numel(upperFace), ...
    face.nUpper,face.nLower,face.gridMismatch, ...
    nAbove,nBelow,hTip,hTip/reference.a0, ...
    min(areas),minAngle,err,postErr, ...
    fitCounts(1),fitCounts(2),fitCounts(3), ...
    'VariableNames',{'originalUpperPolygonVertices', ...
    'generatedUpperT3Nodes','assembledT3Nodes', ...
    'assembledT3Triangles','assembledT6Nodes', ...
    'sharedIntactSeamT3Nodes','upperCrackFaceT3Nodes', ...
    'upperNativeT6FaceNodes','lowerNativeT6FaceNodes', ...
    'faceGridMismatch_m','tipTrianglesAbove','tipTrianglesBelow', ...
    'tipMedianEdge_m','tipMedian_over_a0', ...
    'minCollapsedTriangleArea_m2','minCollapsedT3Angle_deg', ...
    'preCollapseMirrorError_m','postCollapseMirrorError_m', ...
    'n_004_030','n_008_030','n_012_030'});
fprintf('\nSTEP 56 MESH-ONLY REFLECTED ASSEMBLY RESULTS\n');
disp(summary);
disp(gates);
O56=struct('summary',summary,'gates',gates, ...
    'settings',struct('FaceFactor',opt.FaceFactor, ...
       'TipFactor',opt.TipFactor,'Hface',faceSize,'Htip',tipSize, ...
       'tolerance_m',tol), ...
    'step55Source',source, ...
    'refinedReferenceCheckpoint',refCP, ...
    'upperPDEGeometryIDs',struct('face',eFace,'seam',eSeam, ...
       'tip',vTip), ...
    'sourceCrack',s.sourceCrack,'nativeR',r, ...
    'seamT3NodeCount',numel(seam), ...
    'note',['STRUCTURAL / MESH-QUALITY pilot only. The mirrored ', ...
        'triangulation is a NEW candidate, with changed connectivity ', ...
        'compared with original Step45/Step47 meshes.'], ...
    'noNewFEM',true,'noEDI',true);
prefix=char(opt.SavePrefix);
[folder,~,~]=fileparts(prefix);
if ~isempty(folder)&&exist(folder,'dir')~=7,mkdir(folder);end
save([prefix '_small_data.mat'],'O56');
if gates.meshReadyForReview
    % Preserve ACTUAL exact T3 topology and coordinates. A later review
    % may choose this mesh; regeneration or further FEM requires approval.
    candidate=struct('p',p,'t',t, ...
        'crack',crack,'source',source, ...
        'geometryPrescribedBeforeCollapse',D.outerPoly, ...
        'upperHalfPrescribedPolygon',Q, ...
        'provenance',O56.settings, ...
        'noFEMField',true);
    save([prefix '_candidate_T3.mat'],'candidate','-v7.3');
    fprintf('  Exact zero-solve candidate stored: %s\n', ...
        [prefix '_candidate_T3.mat']);
else
    fprintf(['  Structural gate failed: no candidate T3 mesh ', ...
        'was saved for a future FEM calculation.\n']);
end
fprintf('  Compact report saved: %s\n',[prefix '_small_data.mat']);
fprintf('  No FEM solution, stiffness, EDI or physical COD.\n');
end

function yes=whole_edge_is_segment(points,A,B,tol)
AB=B-A;
t=((points(:,1)-A(1))*AB(1)+(points(:,2)-A(2))*AB(2))/ ...
    dot(AB,AB);
projected=A+t*AB;
dist=hypot(points(:,1)-projected(:,1), ...
           points(:,2)-projected(:,2));
yes=max(dist)<=tol && ...
    min(hypot(points(:,1)-A(1),points(:,2)-A(2)))<=tol && ...
    min(hypot(points(:,1)-B(1),points(:,2)-B(2)))<=tol && ...
    all(t>=-tol)&&all(t<=1+tol);
end

function out=mirror(P,y0)
out=P;
out(:,2)=2*y0-P(:,2);
end

function A=triangle_signed(P,T)
a=P(T(:,1),:);b=P(T(:,2),:);c=P(T(:,3),:);
A=.5*((b(:,1)-a(:,1)).*(c(:,2)-a(:,2))- ...
      (c(:,1)-a(:,1)).*(b(:,2)-a(:,2)));
end

function degrees=minimum_angle(P,T)
a=P(T(:,1),:);b=P(T(:,2),:);c=P(T(:,3),:);
l1=hypot(b(:,1)-c(:,1),b(:,2)-c(:,2));
l2=hypot(a(:,1)-c(:,1),a(:,2)-c(:,2));
l3=hypot(a(:,1)-b(:,1),a(:,2)-b(:,2));
cs1=(l2.^2+l3.^2-l1.^2)./(2*l2.*l3);
cs2=(l1.^2+l3.^2-l2.^2)./(2*l1.*l3);
cs3=(l1.^2+l2.^2-l3.^2)./(2*l1.*l2);
angles=acosd(max(-1,min(1,[cs1;cs2;cs3])));
degrees=min(angles);
end