function R65=main_step65_level1_mesh_qualification(varargin)
%MAIN_STEP65_LEVEL1_MESH_QUALIFICATION
% Mesh-only qualification of Level 1 in the calibrated C03 mesh family.
%
% NO physical displacement field is loaded.
% NO stiffness matrix is assembled.
% NO physical FEM solve is performed.
%
% Step65:
%   1) deterministically reconstructs the qualified Level-0 C03 mesh
%      in memory from the committed archived Step62 baseline;
%   2) builds Level 1 with exactly half the structured tip/core scale;
%   3) keeps the same physical geometry, 6-mm paired region and C03
%      exterior calibration (L=8 mm, farSlope=0.10, target ratio=1.8);
%   4) requires all structural/topology/support/grading gates;
%   5) runs only prescribed pure-I, pure-II and KI=1,KII=1e-4 controls;
%   6) saves the Level-1 candidate and compact family-comparison report.
%
% This function never authorizes a physical solve.
%
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
vdir=fullfile(root,'verification');

ip=inputParser;
addParameter(ip,'SourceCandidateFile', ...
    fullfile(vdir,'step62_structured_graded_mesh_candidate_T3.mat'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'SavePrefix', ...
    fullfile(vdir,'step65_c03_family'), ...
    @(s)ischar(s)||(isstring(s)&&isscalar(s)));
addParameter(ip,'Visible','off',@(s)ischar(s)||(isstring(s)&&isscalar(s)));
parse(ip,varargin{:});
opt=ip.Results;

addpath(genpath(root));
assert_step65_branch(root);

sourceFile=char(opt.SourceCandidateFile);
prefix=char(opt.SavePrefix);
if exist(sourceFile,'file')~=2
    error('step65:MissingSource', ...
        'Missing committed archived Step62 baseline candidate: %s',sourceFile);
end

cal=c03_calibration();

fprintf('\n============================================================\n');
fprintf('STEP 65: LEVEL-1 C03 MESH-FAMILY QUALIFICATION — NO PHYSICAL FEM\n');
fprintf('============================================================\n');
fprintf('  Source: committed archived Step62 candidate.\n');
fprintf('  Family calibration: L=8 mm, farSlope=0.10, ratio target=1.8.\n');
fprintf('  Level 1 halves the structured h-law scale: 2^(-1)=0.5.\n');
fprintf('  Physical geometry and paired radius remain unchanged.\n');
fprintf('  Prescribed fields only after structural gates pass.\n');

% -------------------------------------------------------------------------
% Reconstruct Level 0 in memory only. This proves the family definition
% reproduces the already accepted C03 baseline before Level 1 is assessed.
% -------------------------------------------------------------------------
O0=main_step62_structured_graded_mesh( ...
    'SourceCandidateFile',sourceFile, ...
    'SavePrefix',fullfile(vdir,'step65_internal_level0_do_not_write'), ...
    'Visible','off', ...
    'RunSynthetic',false, ...
    'ExteriorCalibration',cal, ...
    'WriteArtifacts',false, ...
    'Verbose',false, ...
    'Level',0);

baselineReproduced= ...
    O0.gates.structuralPass && ...
    O0.summary.newT3==32980 && ...
    O0.summary.newT6Nodes==66854 && ...
    abs(O0.maxNeighborSizeRatio-1.79678451)<=5e-7 && ...
    abs(O0.summary.pairedRadius_mm-6)<=1e-12 && ...
    abs(O0.design.scale-1)<=eps && ...
    O0.design.tipTriangles==6 && ...
    O0.design.tipIncidentTopologicalEdges==7;

if ~baselineReproduced
    error('step65:Level0FamilyMismatch', ...
        ['The current deterministic family definition no longer reproduces ', ...
         'the accepted Level-0 C03 baseline. Stop before Level 1.']);
end

fprintf('  Level-0 C03 reproduction: PASS (T3=%d, T6=%d, ratio=%.9g).\n', ...
    O0.summary.newT3,O0.summary.newT6Nodes,O0.maxNeighborSizeRatio);

% -------------------------------------------------------------------------
% Build Level 1 with full artifacts and prescribed-field qualification.
% main_step62_structured_graded_mesh appends "_L1" to SavePrefix.
% -------------------------------------------------------------------------
O1=main_step62_structured_graded_mesh( ...
    'SourceCandidateFile',sourceFile, ...
    'SavePrefix',prefix, ...
    'Visible',opt.Visible, ...
    'RunSynthetic',true, ...
    'ExteriorCalibration',cal, ...
    'WriteArtifacts',true, ...
    'Verbose',true, ...
    'Level',1);

candidateFile=[prefix '_L1_candidate_T3.mat'];
smallDataFile=[prefix '_L1_small_data.mat'];
overviewFile=[prefix '_L1_overview.png'];
tipFile=[prefix '_L1_tip.png'];

% -------------------------------------------------------------------------
% Family comparison.
% -------------------------------------------------------------------------
level=[0;1];
scale=[O0.design.scale;O1.design.scale];
nT3=[O0.summary.newT3;O1.summary.newT3];
nT6=[O0.summary.newT6Nodes;O1.summary.newT6Nodes];
targetTip_mm=1e3*[O0.targetTipEdge_m;O1.targetTipEdge_m];
actualTipMedian_mm=[O0.summary.newTipMedian_mm;O1.summary.newTipMedian_mm];
pairedRadius_mm=[O0.summary.pairedRadius_mm;O1.summary.pairedRadius_mm];
patchMinAngle_deg=[O0.summary.patchMinAngle_deg;O1.summary.patchMinAngle_deg];
exteriorMinAngle_deg=[O0.summary.exteriorMinAngle_deg;O1.summary.exteriorMinAngle_deg];
maxNeighborRatio=[O0.maxNeighborSizeRatio;O1.maxNeighborSizeRatio];
primarySupport=[O0.summary.newPrimarySupport;O1.summary.newPrimarySupport];
literalSupport=[O0.candidateLiteralSupportCount;O1.candidateLiteralSupportCount];

FamilyComparison=table(level,scale,nT3,nT6,targetTip_mm,actualTipMedian_mm, ...
    pairedRadius_mm,patchMinAngle_deg,exteriorMinAngle_deg, ...
    maxNeighborRatio,primarySupport,literalSupport);

SamplingComparison=table( ...
    O0.samplingTable.lower_r_over_a0, ...
    O0.samplingTable.upper_r_over_a0, ...
    O0.samplingTable.nativePoints, ...
    O1.samplingTable.nativePoints, ...
    'VariableNames',{'lower_r_over_a0','upper_r_over_a0', ...
    'level0NativePoints','level1NativePoints'});

syntheticPerformed=isfield(O1,'synthetic') && ...
    isfield(O1.synthetic,'performed') && O1.synthetic.performed;
syntheticPassed=syntheticPerformed && ...
    isfield(O1.synthetic,'passed') && O1.synthetic.passed;

tipScaleRatio=O1.targetTipEdge_m/O0.targetTipEdge_m;
actualTipRatio=O1.summary.newTipMedian_mm/O0.summary.newTipMedian_mm;

gates=struct();
gates.level0BaselineReproduced=baselineReproduced;
gates.level1StructuralPass=logical(O1.gates.structuralPass);
gates.physicalGeometryUnchanged=logical(O1.gates.physicalGeometryUnchanged);
gates.physicalBoundaryNodesUnchanged=logical(O1.gates.physicalBoundaryNodesUnchanged);
gates.materialUnchanged=logical(O1.gates.materialUnchanged);
gates.completeT3Pairing=logical(O1.gates.completeT3Pairing);
gates.completeT6Pairing=logical(O1.gates.completeT6Pairing);
gates.supportInsidePairedRegion=logical(O1.gates.candidateSupportInsidePairedRegion);
gates.exteriorOutsideSupport=logical(O1.gates.exteriorOutsideSupport);
gates.tipFanSixTriangles=logical(O1.gates.tipFanSixTriangles);
gates.tipScaleExactlyHalved=abs(tipScaleRatio-.5)<=1e-12;
gates.actualTipScaleHalved=abs(actualTipRatio-.5)<=.02;
gates.samePairedRadius=abs(O1.summary.pairedRadius_mm-O0.summary.pairedRadius_mm)<=1e-12;
gates.gradingTarget18=O1.maxNeighborSizeRatio<=1.8+5e-12;
gates.minimumAngle20deg=logical(O1.gates.minimumAngle20deg);
gates.nativeSamplingNotReduced=all( ...
    O1.samplingTable.nativePoints>=O0.samplingTable.nativePoints);
gates.syntheticPerformed=syntheticPerformed;
gates.syntheticPassed=syntheticPassed;
gates.zeroPhysicalFEM=logical(O1.noFEM)&&logical(O1.noPhysicalU)&&logical(O1.noStiffness);

familyQualified=all(structfun(@(x)logical(x),gates));
readyForOneLevel1FEMProposal=familyQualified && ...
    O1.readyForOneAsymmetricFEMProposal;

fprintf('\nLEVEL-0 vs LEVEL-1 FAMILY COMPARISON\n');
disp(FamilyComparison);
fprintf('\nNATIVE COD SAMPLING COMPARISON\n');
disp(SamplingComparison);
fprintf('\nSTEP65 FAMILY GATES\n');
disp(gates);
if syntheticPerformed
    fprintf('\nLEVEL-1 PRESCRIBED-FIELD QUALIFICATION\n');
    disp(O1.synthetic.table);
end

if familyQualified
    fprintf('STEP65 PASS: Level 1 is a qualified member of the C03 family.\n');
    fprintf('  Candidate: %s\n',candidateFile);
    fprintf('  NO physical FEM solve has been performed.\n');
    fprintf('  Level-1 physical solve is only a future proposal.\n');
else
    fprintf('STEP65 STOP: one or more mesh-family qualification gates failed.\n');
    fprintf('  NO physical FEM solve has been performed or proposed as ready.\n');
end

R65=struct( ...
    'sourceCandidateFile',sourceFile, ...
    'calibration',cal, ...
    'level0',O0, ...
    'level1',O1, ...
    'FamilyComparison',FamilyComparison, ...
    'SamplingComparison',SamplingComparison, ...
    'gates',gates, ...
    'tipScaleRatio',tipScaleRatio, ...
    'actualTipRatio',actualTipRatio, ...
    'familyQualified',familyQualified, ...
    'readyForOneLevel1FEMProposal',readyForOneLevel1FEMProposal, ...
    'candidateFile',candidateFile, ...
    'level1SmallDataFile',smallDataFile, ...
    'overviewFile',overviewFile, ...
    'tipFile',tipFile, ...
    'noPhysicalFEM',true, ...
    'noPhysicalU',true, ...
    'interpretation',['Level-1 mesh-family qualification only. ', ...
      'Prescribed fields test extraction/topology; they do not establish ', ...
      'physical KII convergence.']);

reportFile=[prefix '_qualification_small_data.mat'];
save(reportFile,'R65','-v7');
fprintf('  Compact Step65 qualification report: %s\n',reportFile);
end

function cal=c03_calibration()
cal=struct( ...
    'transitionLength_m',.008, ...
    'farSlope',.10, ...
    'boundaryMetricGrowth',.25, ...
    'smoothingSteps',6, ...
    'refinementMaxPasses',140, ...
    'refinementMinAngle_deg',25, ...
    'refinementLongestFactor',1.65, ...
    'neighborRatioTarget',1.8, ...
    'verbose',false);
end

function assert_step65_branch(root)
[status,b]=system(sprintf('git -C "%s" branch --show-current',root));
assert(status==0&&strcmp(strtrim(b),'audit/step65-level1-mesh-qualification'), ...
    'step65:Branch', ...
    'Run Step65 only on audit/step65-level1-mesh-qualification.');
end
