function O46=main_step46_symmetric_mesh_preflight(varargin)
%MAIN_STEP46_SYMMETRIC_MESH_PREFLIGHT
% Step 46, MESH-ONLY pilot, using the established centered-hole theta=0
% control. NO FEM solve, stiffness assembly or interaction EDI.
%
% Goal: hold the SAME polygonal hole, plate, loading configuration and
% horizontal crack while reducing only the REQUESTED crack-face/tip
% characteristic mesh sizes. Inspect the actual generated meshes before
% deciding whether one refined symmetric FEM solution is worth running.
%
% This is not a matched-exterior-connectivity experiment: PDE generateMesh
% may also change triangle locations away from the tip. It is a
% SAME-GEOMETRY LOCAL-REFINEMENT REQUEST, not proof of isolated tip error.
%
% From a MATLAB session after pulling sif-asymmetric-mesh-audit:
%   addpath(genpath(pwd));
%   O46=main_step46_symmetric_mesh_preflight();
%   disp(O46.meshTable); disp(O46.gates);
%
% Requires the LOCAL saved Step45 control checkpoint already generated by
% the investigator. Computes a fresh baseline geometry/mesh without a
% solve solely to identify exact sharp-pencil geometry IDs. Uses the SAME
% D description for the refined mesh and reidentifies pencil edge/vertex
% IDs after manual remeshing. Aborts rather than trusting unverified IDs.
%
% Does NOT save large PDE models or meshes and cannot trigger a FEM solve.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
defaultCP=fullfile(root,'verification', ...
    'step45_symmetric_theta0_solved.mat');
ip=inputParser;
addParameter(ip,'ReferenceCheckpoint',defaultCP, ...
    @(x)ischar(x)||(isstring(x)&&isscalar(x)));
addParameter(ip,'FaceFactor',0.5, ...
    @(x)isnumeric(x)&&isscalar(x)&&isfinite(x)&&x>0&&x<1);
addParameter(ip,'TipFactor',0.5, ...
    @(x)isnumeric(x)&&isscalar(x)&&isfinite(x)&&x>0&&x<1);
addParameter(ip,'SavePath',fullfile(root,'verification', ...
    'step46_mesh_preflight_small_data.mat'), ...
    @(x)ischar(x)||(isstring(x)&&isscalar(x)));
parse(ip,varargin{:});
opt=ip.Results;
addpath(genpath(root));
cp=char(opt.ReferenceCheckpoint);
if exist(cp,'file')~=2
    error('step46:MissingBaseline', ...
        'Local Step45 symmetric control checkpoint is required: %s',cp);
end
s=load(cp,'mesh','mat','crack','a0','meta');
for field={'mesh','mat','crack','a0','meta'}
    must(s,field{1});
end
if ~isfield(s.meta,'caseType') || ...
        ~strcmp(s.meta.caseType,'step45_centered_half_theta0') || ...
        ~isfield(s.meta,'Npoly')
    error('step46:WrongCheckpoint', ...
        'Expected previously saved Step45 centered theta=0 checkpoint.');
end
nPoly=s.meta.Npoly;
a0=s.a0;
if ~isfield(s.mesh,'coord3') || ~isfield(s.mesh,'connect3') || ...
        size(s.mesh.connect3,2)~=3 || ...
        abs(s.crack.Pmid(end,2)-s.crack.Pmid(1,2))>1e-12
    error('step46:InvalidReferenceMesh', ...
        'The reference must contain a horizontal T3/T6 control mesh.');
end
if ~isequal(nPoly,240) || abs(a0-0.004)>1e-12
    error('step46:ChangedReferenceSetup', ...
        'This pilot is for the already measured Npoly=240, a0=0.004 m control.');
end

C=cfg_centered_half_domain();
C.hole.npoly=nPoly;
C.holes={C.hole};
C.a0=a0;
hArc=2*pi*C.hole.r/nPoly;
C.mesh1.hmin=hArc;
C.mesh1.hhole=hArc;
C.mesh1.hmax=20*hArc;
C.mesh2.hmax=C.mesh1.hmax;
C.mesh2.hhole=C.mesh1.hmin;
C.mesh2.hcrack=C.mesh1.hmin;
C.solver.verbose=0;
mouth=[C.hole.center(1)+C.hole.r,C.hole.center(2)];
expectedPmid=[mouth;mouth+[a0,0]];
if norm(s.crack.Pmid-expectedPmid,'fro')>1e-10
    error('step46:ReferenceGeometryMismatch', ...
        'The saved FEM crack does not match the prescribed baseline geometry.');
end
fprintf('\n============================================================\n');
fprintf('STEP 46 PREFLIGHT: SAME GEOMETRY, SMALLER TIP/FACE MESH SIZES\n');
fprintf('============================================================\n');
fprintf('  Old checkpoint: %s\n',cp);
fprintf('  Baseline: Npoly=%d, a0=%.8g m, hArc=%.9g m\n', ...
    nPoly,a0,hArc);
fprintf('  NO FEM solution, stiffness assembly or EDI will be performed.\n');

% First reproduce BASELINE geometry and obtain geometry IDs using the
% existing tested Step45 centered mesh builder. This generates a mesh
% (and can invoke its temporary geometry-ID fallback) but does not solve.
[~,D,Mbase,McBase]=build_stage2_centered_half_cracked_mesh_for_theta( ...
    C,struct(),0,'PlotGeom',false,'PlotMesh',false, ...
    'PlotCollapsed',false);
if ~isfield(Mbase.region,'geomIDs') || ...
        isempty(Mbase.region.geomIDs) || ...
        ~isfield(Mbase.region.geomIDs,'e_tip') || ...
        ~isfield(Mbase.region.geomIDs,'v_tip')
    error('step46:MissingPencilIDs', ...
        'Could not recover baseline pencil vertex and both face edge IDs.');
end
ids=Mbase.region.geomIDs;
if numel(ids.e_tip)~=2 || numel(ids.v_tip)~=1 || ...
        norm(D.Pmid-expectedPmid,'fro')>1e-12
    error('step46:BadPencilGeometry', ...
        'Inconsistent baseline pencil geometry or geometry IDs.');
end
if norm(McBase.crack.Pmid-s.crack.Pmid,'fro')>1e-12
    error('step46:BaselineCrackChanged','Baseline crack geometry changed.');
end
fprintf('  Recovered pencil edge IDs [%d %d], tip vertex ID %d\n', ...
    ids.e_tip(1),ids.e_tip(2),ids.v_tip);

% Reuse the EXACT SAME D, polygon and crack; override only requested
% manual edge and tip sizes at identified PDE geometry edges/vertex.
faceRequested=opt.FaceFactor*hArc;
tipRequested=opt.TipFactor*0.5*hArc;
fprintf('  New local requested Hface=%.9g m (%.3g x baseline)\n', ...
    faceRequested,opt.FaceFactor);
fprintf('  New local requested Htip =%.9g m (%.3g x baseline)\n', ...
    tipRequested,opt.TipFactor);
Mref=mesh_hole_pencil_domain(D, ...
    'Hmin',C.mesh1.hmin, ...
    'Hmax',C.mesh1.hmax, ...
    'Hgrad',C.mesh1.hgrad, ...
    'Hedge',{ids.e_tip,faceRequested}, ...
    'Hvertex',{ids.v_tip,tipRequested}, ...
    'PlotGeom',false,'PlotMesh',false);
if ~isfield(Mref.region,'geomIDs') || isempty(Mref.region.geomIDs) ...
        || ~isfield(Mref.region.geomIDs,'e_tip') || ...
        ~isfield(Mref.region.geomIDs,'v_tip') || ...
        numel(Mref.region.geomIDs.e_tip)~=2 || ...
        ~isequal(sort(Mref.region.geomIDs.e_tip(:)),sort(ids.e_tip(:))) || ...
        Mref.region.geomIDs.v_tip~=ids.v_tip
    error('step46:ManualGeometryIDMismatch', ...
        ['Manual refined mesh could not independently confirm the ', ...
         'exact same pencil vertex and face edge IDs. ', ...
         'NO FEM solve was attempted.']);
end
McRef=collapse_pencil_faces_to_midline(Mref,D, ...
    'EdgeIDs',ids.e_tip,'TipVertexID',ids.v_tip);
if norm(McRef.crack.Pmid-s.crack.Pmid,'fro')>1e-12
    error('step46:RefinedCrackChanged','Refined crack geometry changed.');
end
fprintf('  Same domain struct D and exact crack coordinates verified.\n');

% Compare OLD saved solved mesh topology, NEW reproduced baseline mesh,
% and NEW locally refined mesh (all are evaluated with zero displacements,
% so NO physical displacements are invented or numerical results inferred).
[mb,profileSaved]=local_measure(s.mesh,s.crack,s.mat,a0);
meshBase=local_make_mesh(McBase);
[mm,profileRegenerated]=local_measure(meshBase,McBase.crack,s.mat,a0);
clear meshBase
meshRef=local_make_mesh(McRef);
[mr,profileRefined]=local_measure(meshRef,McRef.crack,s.mat,a0);
clear meshRef

nOld=size(s.mesh.coord3,1);
nFresh=size(McBase.p,1);
sameCoord=NaN;
if nOld==nFresh
    Pold=sortrows(s.mesh.coord3,[1 2]);
    Pnew=sortrows(McBase.p,[1 2]);
    sameCoord=max(abs(Pold(:)-Pnew(:)));
end
sameTri=size(s.mesh.connect3,1)==size(McBase.t,1);
fprintf('  Fresh baseline reproduces old T3 count: %s\n',mat2str(sameTri));
fprintf('  Old vs fresh baseline sorted T3 coordinate discrepancy: %.9g m\n', ...
    sameCoord);
if ~sameTri || ~isfinite(sameCoord) || sameCoord>1e-10
    warning('step46:BaselineMeshingDifference', ...
        ['New automatic baseline mesh differs from saved old mesh. ', ...
         'Identical PDE geometry and configuration were prescribed, ', ...
         'but the external triangulation may not reproduce bitwise.']);
end

rows=[mb;mm;mr];
source={'Saved Step45';'Rebuilt baseline';'Refined request'};
T=table(source,rows(:,1),rows(:,2),rows(:,3),rows(:,4), ...
    rows(:,5),rows(:,6),rows(:,7),rows(:,8),rows(:,9), ...
    rows(:,10),rows(:,11),rows(:,12), ...
    'VariableNames',{'mesh','nT3','nT6','hTipMedian_m', ...
    'hTip_over_a0','tipTrianglesAbove','tipTrianglesBelow', ...
    'upperFaceNative','lowerFaceNative','faceGridMismatch_m', ...
    'n_004_030','n_008_030','n_012_030'});
maxFaceTol=max(1e-12,1e-8*a0);
gates=struct( ...
    'samePrescribedPolygonAndCrack',true, ...
    'baselineMeshReproducesSaved',sameTri && ...
        isfinite(sameCoord) && sameCoord<1e-10, ...
    'faceMismatchAcceptable', ...
        isfinite(mr(9)) && mr(9)<=maxFaceTol, ...
    'tipMedianReduced',mr(3)<0.7*mb(3), ...
    'moreNativeCODInWideWindow',mr(10)>mb(10), ...
    'wideWindowLinearFitHasEightNodes',mr(10)>=8, ...
    'wideWindowQuadraticFitHasTwelveNodes',mr(10)>=12, ...
    'readyForOneRefinedFEMProposal',false);
gates.readyForOneRefinedFEMProposal= ...
    gates.faceMismatchAcceptable && gates.tipMedianReduced && ...
    gates.moreNativeCODInWideWindow && ...
    gates.samePrescribedPolygonAndCrack;

O46=struct('settings',opt,'baselineCheckpointPath',cp, ...
    'Npoly',nPoly,'a0',a0,'baselineHArc',hArc, ...
    'faceRequested',faceRequested,'tipRequested',tipRequested, ...
    'originalPencilIDs',struct('edge',ids.e_tip,'tip',ids.v_tip), ...
    'baselineReproducedCoordError',sameCoord, ...
    'meshTable',T,'gates',gates, ...
    'nativeRSaved',profileSaved, ...
    'nativeRBaselineRegenerated',profileRegenerated, ...
    'nativeRRefined',profileRefined);
saveFile=char(opt.SavePath);
[folder,~,~]=fileparts(saveFile);
if ~isempty(folder)&&exist(folder,'dir')~=7,mkdir(folder);end
save(saveFile,'O46'); % compact ONLY: no FEM mesh, U or PDE objects

fprintf('\nSTEP 46 MESH PREFLIGHT RESULTS (no FEM solve):\n');
disp(T);
disp(gates);
fprintf('  Compact report saved to %s\n',saveFile);
fprintf(['  The pilot does not prove mesh-to-mesh equality outside the ', ...
    'tip region; compare actual generated meshes/field only ', ...
    'after a separate, explicitly approved refinement solve.\n']);
end

function m=local_make_mesh(Mc)
if size(Mc.t,2)~=3
    error('step46:ExpectedT3','Mesh-only pilot expected T3 PDE triangles.');
end
[coord,tria6]=T3toT6_fast(Mc.p,Mc.t);
m=struct('coord3',Mc.p,'connect3',Mc.t, ...
    'coord',coord,'connect',tria6);
end

function [metrics,r]=local_measure(mesh,crack,mat,a0)
if size(mesh.connect,2)~=6 || size(mesh.connect3,2)~=3
    error('step46:ExpectedT6','Preflight needs both T3 and T6 topology.');
end
[r,~,face]=native_COD_audit( ...
    mesh,zeros(2*size(mesh.coord,1),1),mat,crack,2);
tip=crack.Pmid(end,:);
P=mesh.coord3;tri=mesh.connect3;
tol=max(1e-12,1e-8*max(1,max(abs(P(:)))));
distance=hypot(P(:,1)-tip(1),P(:,2)-tip(2));
tipIds=find(distance<=min(distance)+tol);
near=tri(any(ismember(tri,tipIds),2),:);
if isempty(near),error('step46:NoTipElements','Missing tip triangles.');end
p1=P(near(:,1),:);p2=P(near(:,2),:);p3=P(near(:,3),:);
% A collapsed-pencil T3 should remain nondegenerate. Reject a mesh that
% could appear more refined numerically but would be invalid for FEM.
v12=P(tri(:,2),:)-P(tri(:,1),:);
v13=P(tri(:,3),:)-P(tri(:,1),:);
area=0.5*abs(v12(:,1).*v13(:,2)-v12(:,2).*v13(:,1));
if ~all(isfinite(area)) || min(area)<1e-18
    error('step46:DegenerateCollapsedMesh', ...
        'Collapsed mesh contains degenerate or invalid T3 elements.');
end
L=[hypot(p1(:,1)-p2(:,1),p1(:,2)-p2(:,2)); ...
   hypot(p2(:,1)-p3(:,1),p2(:,2)-p3(:,2)); ...
   hypot(p3(:,1)-p1(:,1),p3(:,2)-p1(:,2))];
L=L(isfinite(L)&L>tol);
hTip=median(L);
centroid=(p1+p2+p3)/3;
above=nnz(centroid(:,2)>tip(2)+tol);
below=nnz(centroid(:,2)<tip(2)-tol);
x=r/a0;
metrics=[size(tri,1),size(mesh.coord,1),hTip,hTip/a0, ...
    above,below,face.nUpper,face.nLower,face.gridMismatch, ...
    nnz(x>=.04&x<=.30),nnz(x>=.08&x<=.30), ...
    nnz(x>=.12&x<=.30)];
end

function must(s,field)
if ~isstruct(s)||~isfield(s,field)||isempty(s.(field))
    error('step46:MissingCheckpointField', ...
        'Baseline checkpoint is missing %s.',field);
end
end
