function [P47,O47]=main_step47_local(varargin)
%MAIN_STEP47_LOCAL  One explicitly authorized refined symmetric Stage-II
% solve, *only* after reproducing the selected Step-46 mesh-only preflight.
% Defaults: NO new FEM solve, NO EDI. Always reuses an existing recognized
% Step-47 checkpoint. After checkpointing, performs native COD ONLY.
%
% GitHub Desktop: pull sif-asymmetric-mesh-audit before using.
%  addpath(genpath(pwd));
%  [P47,O47]=main_step47_local(); % safe: refuses new solve
%  % When the investigator APPROVES exactly one FEM solve:
%  [P47,O47]=main_step47_local('AllowSolve',true);
%
% Requires LOCAL Step46 selected 0.125-face/0.5-tip preflight file.
% Does NOT create an independent new physical-geometry experiment. The
% 16-point EDI run, if later approved, is a separate opt-in postprocessor.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
vDir=fullfile(root,'verification');
ip=inputParser;
addParameter(ip,'AllowSolve',false,@(x)islogical(x)&&isscalar(x));
addParameter(ip,'PreflightFile', ...
    fullfile(vDir,'step46_mesh_preflight_face0125_tip05.mat'), ...
    @(x)ischar(x)||(isstring(x)&&isscalar(x)));
addParameter(ip,'CheckpointFile', ...
    fullfile(vDir,'step47_refined_symmetric_theta0_solved.mat'), ...
    @(x)ischar(x)||(isstring(x)&&isscalar(x)));
parse(ip,varargin{:});
opt=ip.Results;
addpath(genpath(root));
selFile=char(opt.PreflightFile);
cp=char(opt.CheckpointFile);
if exist(selFile,'file')~=2
    error('step47:MissingSelectedPreflight', ...
        'First run Step46 0.125/0.5 preflight. Missing file: %s',selFile);
end
v=load(selFile,'O46');
if ~isfield(v,'O46')
    error('step47:PreflightFormat','Expected O46 in selected preflight MAT.');
end
S=v.O46;
for f={'settings','baselineCheckpointPath','meshTable','gates', ...
        'nativeRRefined','a0','Npoly','baselineHArc','originalPencilIDs'}
    must(S,f{1});
end
if abs(S.settings.FaceFactor-0.125)>1e-12 || ...
        abs(S.settings.TipFactor-0.5)>1e-12 || ...
        S.Npoly~=240 || abs(S.a0-0.004)>1e-12 || ...
        ~S.gates.samePrescribedPolygonAndCrack || ...
        ~S.gates.baselineMeshReproducesSaved || ...
        ~S.gates.faceMismatchAcceptable || ...
        ~S.gates.wideWindowQuadraticFitHasTwelveNodes || ...
        height(S.meshTable)~=3
    error('step47:PreflightNotApproved', ...
        'Selection must be the VERIFIED Step46 face=0.125 tip=0.5 mesh.');
end
T=S.meshTable;
selected=T(3,:);
if selected.n_004_030<12 || selected.n_008_030<12 || ...
        selected.n_012_030<12 || ...
        selected.hTip_over_a0>=0.05 || ...
        selected.upperFaceNative~=selected.lowerFaceNative || ...
        selected.faceGridMismatch_m>max(1e-12,1e-8*S.a0)
    error('step47:InsufficientSelectedMesh', ...
        'Selected mesh must satisfy all original quadratic COD windows.');
end
refcp=char(S.baselineCheckpointPath);
if exist(refcp,'file')~=2
    error('step47:OriginalCheckpointAbsent', ...
        'Original saved Step45 symmetric field is required: %s',refcp);
end
if strcmpi(cp,refcp)
    error('step47:CannotOverwriteBaseline', ...
        'Step47 checkpoint must NOT overwrite original Step45 checkpoint.');
end
ref=load(refcp,'mesh','mat','crack','a0','meta');
for f={'mesh','mat','crack','a0','meta'}
    must(ref,f{1});
end
if ~strcmp(ref.meta.caseType,'step45_centered_half_theta0') || ...
        ref.meta.Npoly~=S.Npoly || abs(ref.a0-S.a0)>1e-12
    error('step47:BaselineMismatch', ...
        'Original saved symmetric field/checkpoint no longer matches preflight.');
end
% Exact recipe provenance is checked on every run, including when the
% refined checkpoint already exists. Never silently replace or overwrite.
if exist(cp,'file')==2
    d=load(cp,'meta','a0');
    if ~isfield(d,'meta') || ~isfield(d.meta,'stage') || ...
            ~strcmp(d.meta.stage,'step47_refined_control') || ...
            ~isfield(d.meta,'faceFactor') || ...
            abs(d.meta.faceFactor-0.125)>1e-12 || ...
            abs(d.meta.tipFactor-0.5)>1e-12 || ...
            ~isfield(d.meta,'nativeRSelected') || ...
            numel(d.meta.nativeRSelected)~=numel(S.nativeRRefined) || ...
            max(abs(d.meta.nativeRSelected(:)-S.nativeRRefined(:)))>1e-12
        error('step47:ExistingCheckpointMismatch', ...
            'Existing checkpoint is not verified Step47 selected mesh.');
    end
    fprintf('STEP 47: reusing previously saved one-solve checkpoint.\n');
    P47=struct('checkpointPath',cp,'reusedFile',true, ...
        'newSolve',false,'meta',d.meta);
else
    if ~opt.AllowSolve
        error('step47:ExplicitSolveApprovalRequired', ...
            ['Selected Step46 mesh is eligible, but no new FEM solve ', ...
            'was authorized. To approve exactly ONE Stage-II solve, ', ...
            'run main_step47_local(''AllowSolve'',true).']);
    end
    fprintf('\n============================================================\n');
    fprintf('STEP 47: VERIFY SELECTED REFINED MESH BEFORE ONE FEM SOLVE\n');
    fprintf('============================================================\n');
    C=cfg_centered_half_domain();
    C.hole.npoly=S.Npoly;
    C.holes={C.hole};
    C.a0=S.a0;
    hArc=2*pi*C.hole.r/S.Npoly;
    if abs(hArc-S.baselineHArc)>1e-12
        error('step47:ArcChanged','Nominal polygonal geometry changed.');
    end
    C.mesh1.hmin=hArc;
    C.mesh1.hhole=hArc;
    C.mesh1.hmax=20*hArc;
    C.mesh2.hmax=C.mesh1.hmax;
    C.mesh2.hhole=C.mesh1.hmin;
    C.mesh2.hcrack=C.mesh1.hmin;
    C.solver.verbose=0;
    if abs(C.E-ref.mat.E)>1e-10*max(1,abs(ref.mat.E)) || ...
            abs(C.nu-ref.mat.nu)>1e-12 || ...
            C.ps~=ref.mat.ps || ...
            ~strcmp(C.domain.mode,'centered_right_half') || ...
            ~strcmp(C.load.type,'remote_tension_y') || ...
            ~strcmp(C.bc.anchor_mode,'symmetry_half_x')
        error('step47:PhysicalSetupChanged', ...
            'Current configuration/material does not match symmetric baseline.');
    end

    % First regenerate ORIGINAL mesh and identify the exact pencil geometry
    % IDs by the established fallback if necessary. Then apply the SELECTED
    % manual refinement to the SAME D struct (not reconstructed geometry).
    [~,D,Mbase,McBase]=build_stage2_centered_half_cracked_mesh_for_theta( ...
        C,struct(),0,'PlotGeom',false,'PlotMesh',false, ...
        'PlotCollapsed',false);
    ids=Mbase.region.geomIDs;
    if isempty(ids)||~isfield(ids,'e_tip')||~isfield(ids,'v_tip')|| ...
            ~isequal(ids.e_tip(:),S.originalPencilIDs.edge(:)) || ...
            ids.v_tip~=S.originalPencilIDs.tip
        error('step47:PencilIDsChanged','Baseline geometry edge IDs differ.');
    end
    if size(McBase.p,1)~=size(ref.mesh.coord3,1) || ...
            size(McBase.t,1)~=size(ref.mesh.connect3,1) || ...
            max(abs(sortrows(McBase.p,[1 2])- ...
                sortrows(ref.mesh.coord3,[1 2])),[],'all')>1e-10
        error('step47:BaselineMeshNotReproduced', ...
            'Refuse solve: original saved mesh was not reproduced.');
    end
    Mref=mesh_hole_pencil_domain(D, ...
        'Hmin',C.mesh1.hmin,'Hmax',C.mesh1.hmax, ...
        'Hgrad',C.mesh1.hgrad, ...
        'Hedge',{ids.e_tip,0.125*hArc}, ...
        'Hvertex',{ids.v_tip,0.5*0.5*hArc}, ...
        'PlotGeom',false,'PlotMesh',false);
    got=Mref.region.geomIDs;
    if isempty(got)||~isfield(got,'e_tip')||~isfield(got,'v_tip') || ...
            ~isequal(sort(got.e_tip(:)),sort(ids.e_tip(:))) || ...
            got.v_tip~=ids.v_tip
        error('step47:RefinedPencilIDsMismatch', ...
            'Cannot verify identical pencil geometry after manual remeshing.');
    end
    Mc=collapse_pencil_faces_to_midline(Mref,D, ...
        'EdgeIDs',ids.e_tip,'TipVertexID',ids.v_tip);
    if norm(Mc.crack.Pmid-ref.crack.Pmid,'fro')>1e-12
        error('step47:CrackChanged','Refined crack geometry does not match.');
    end
    if size(Mc.t,2)~=3
        error('step47:NoT3Mesh','Expected T3 before upgrading to T6.');
    end
    % Mesh-only metrics must match ALL stored selected preflight metrics,
    % including its actual native COD radius list, not only requested sizes.
    [coord6,conn6]=T3toT6_fast(Mc.p,Mc.t);
    meshTry=struct('coord3',Mc.p,'connect3',Mc.t, ...
        'coord',coord6,'connect',conn6);
    [r,~,face]=native_COD_audit(meshTry, ...
        zeros(2*size(coord6,1),1),ref.mat,Mc.crack,2);
    if size(Mc.t,1)~=selected.nT3 || ...
            size(coord6,1)~=selected.nT6 || ...
            face.nUpper~=selected.upperFaceNative || ...
            face.nLower~=selected.lowerFaceNative || ...
            abs(face.gridMismatch)>max(1e-12,1e-8*S.a0) || ...
            numel(r)~=numel(S.nativeRRefined) || ...
            max(abs(r(:)-S.nativeRRefined(:)))>1e-12
        error('step47:RefinedMeshNotReproduced', ...
            'Requested refinement did not reproduce verified native samples.');
    end
    tip=Mc.crack.Pmid(end,:);
    P=Mc.p; t=Mc.t;
    dr=hypot(P(:,1)-tip(1),P(:,2)-tip(2));
    tol=max(1e-12,1e-8*max(1,max(abs(P(:)))));
    tipIDs=find(dr<=min(dr)+tol);
    near=t(any(ismember(t,tipIDs),2),:);
    a=P(near(:,1),:);b=P(near(:,2),:);c=P(near(:,3),:);
    edges=[hypot(a(:,1)-b(:,1),a(:,2)-b(:,2)); ...
           hypot(b(:,1)-c(:,1),b(:,2)-c(:,2)); ...
           hypot(c(:,1)-a(:,1),c(:,2)-a(:,2))];
    edges=edges(edges>tol);
    hTip=median(edges);
    centers=(a+b+c)/3;
    above=nnz(centers(:,2)>tip(2)+tol);
    below=nnz(centers(:,2)<tip(2)-tol);
    if ~isfinite(hTip)||abs(hTip-selected.hTipMedian_m)>1e-10 || ...
            above~=selected.tipTrianglesAbove || ...
            below~=selected.tipTrianglesBelow || ...
            numel(r(r/S.a0>=.04 & r/S.a0<=.30))~=selected.n_004_030 || ...
            numel(r(r/S.a0>=.08 & r/S.a0<=.30))~=selected.n_008_030 || ...
            numel(r(r/S.a0>=.12 & r/S.a0<=.30))~=selected.n_012_030
        error('step47:MeasuredMeshNotReproduced', ...
            'Tip edge/fan or native COD fit counts differ from Step46.');
    end
    v12=P(t(:,2),:)-P(t(:,1),:);
    v13=P(t(:,3),:)-P(t(:,1),:);
    areas=abs(v12(:,1).*v13(:,2)-v12(:,2).*v13(:,1))/2;
    if any(~isfinite(areas))||min(areas)<1e-18
        error('step47:DegenerateRefinedMesh', ...
            'Refined collapsed mesh has a degenerate triangle.');
    end
    fprintf(['  VERIFIED candidate: T3=%d, T6=%d, tip h=%.9g m, ', ...
        'native face nodes=%d/%d, COD windows=%d/%d/%d\n'], ...
        size(t,1),size(coord6,1),hTip,face.nUpper,face.nLower, ...
        selected.n_004_030,selected.n_008_030,selected.n_012_030);
    fprintf('  Starting exactly ONE approved Stage-II FEM solve.\n');
    clear meshTry coord6 conn6 Mref Mbase McBase ref;
    S2=solve_cracked_LEFM(C,Mc,'lambda',1.0);
    if ~isfield(S2,'mesh')||~isfield(S2,'U') || ...
            numel(S2.U)~=2*size(S2.mesh.coord,1) || ...
            size(S2.mesh.coord,1)~=selected.nT6 || ...
            any(~isfinite(S2.U))
        error('step47:InvalidSolvedField', ...
            'The refined Stage-II FEM solution failed checkpoint checks.');
    end
    % Ensure the FEM solver operated on precisely the accepted regenerated
    % candidate T3 coordinates/connectivity, before saving any results.
    if ~isequal(S2.mesh.connect3,Mc.t) || ...
            ~isequal(size(S2.mesh.coord3),size(Mc.p)) || ...
            max(abs(S2.mesh.coord3(:)-Mc.p(:)))>1e-12
        error('step47:SolvedMeshMismatch', ...
            'FEM solution was not computed on verified candidate T3 mesh.');
    end
    mesh=S2.mesh;U=S2.U;mat=S2.mat;
    crack=Mc.crack;a0=S.a0;
    meta=struct('caseType','step45_centered_half_theta0', ...
        'stage','step47_refined_control', ...
        'source','one explicitly authorized refined Stage-II FEM solve', ...
        'Npoly',S.Npoly,'a0',a0,'zeroAngleDeg',0, ...
        'nT6',size(mesh.coord,1),'nT3',size(mesh.connect3,1), ...
        'faceFactor',0.125,'tipFactor',0.5, ...
        'hTipSelected',hTip,'nativeRSelected',S.nativeRRefined(:), ...
        'preflightFile',selFile,'baselineCheckpoint',refcp, ...
        'symmetryExpectation','KII=0 in symmetric continuum', ...
        'previousStep18EDI',struct('available',false));
    clear S2 Mc C D S v
    [folder,~,~]=fileparts(cp);
    if ~isempty(folder)&&exist(folder,'dir')~=7,mkdir(folder);end
    tmp=[cp '.incomplete.mat'];
    if exist(tmp,'file')==2
        error('step47:InterruptedPriorSave', ...
            'Existing incomplete checkpoint must be inspected: %s',tmp);
    end
    save(tmp,'mesh','U','mat','crack','a0','meta','-v7.3');
    [ok,msg]=movefile(tmp,cp);
    if ~ok,error('step47:CheckpointSaveFailed','%s',msg);end
    fprintf('  Saved unique refined checkpoint: %s\n',cp);
    P47=struct('checkpointPath',cp,'reusedFile',false, ...
        'newSolve',true,'meta',meta);
    clear mesh U mat
end

% COD-only phase reuses the verified Step45 numerical body. This produces
% ALL predeclared linear/quadratic windows before any EDI is requested.
fprintf('STEP 47: running COD ONLY on selected refined FEM field.\n');
O47=main_step45_symmetric_field_leakage(P47, ...
    'RunEDI',false, ...
    'SavePrefix',fullfile(vDir,'step47_refined_symmetric_field_leakage'));
fprintf('\nSTEP 47: COD extrapolations for investigation:\n');
disp(O47.fitTable);
disp(O47.CODgates);
fprintf('  EDI was not run; await analysis before any EDI integrations.\n');
end

function must(s,name)
if ~isstruct(s)||~isfield(s,name)||isempty(s.(name))
    error('step47:MissingInput','Missing required %s in selected preflight.',name);
end
end
