function P = build_tip_submodel_from_global(Sglobal, Rpatch, varargin)
%BUILD_TIP_SUBMODEL_FROM_GLOBAL  Symmetric cracked-disk submodel around V2.
%
% The outer displacement boundary condition is interpolated from a solved
% global two-leg benchmark.  Inside the disk, the crack is the straight
% continuation of Leg 2 behind the tip.  Rpatch must be smaller than delta
% so the knee V1 is outside the submodel.
%
% This construction gives an exactly mirror-paired LOCAL mesh when
% AsymmetryLevel=0 while preserving the physical mixed-mode boundary data
% generated by the full two-leg problem.
%
% Name-value options
%   'Nr'              radial rings, default 10
%   'Ntheta'          angular sectors, default 64 (must be even)
%   'RadialPower'     r_j/R=(j/Nr)^p, default 1.35
%   'AsymmetryLevel'  upper-side interior perturbation / h_ref, default 0
%
% Output P
%   .mesh, .U, .mat, .V, .Rpatch
%   .meshInfo and .bcInfo

    ip=inputParser;
    addParameter(ip,'Nr',10,@(x)isnumeric(x)&&isscalar(x)&&x>=3);
    addParameter(ip,'Ntheta',64,@(x)isnumeric(x)&&isscalar(x)&&x>=16);
    addParameter(ip,'RadialPower',1.35,@(x)isnumeric(x)&&isscalar(x)&&x>=1);
    addParameter(ip,'AsymmetryLevel',0,@(x)isnumeric(x)&&isscalar(x)&&x>=0);
    parse(ip,varargin{:});

    C=Sglobal.C;
    if ~(Rpatch>0 && Rpatch<0.95*C.delta)
        error('build_tip_submodel_from_global:BadRadius', ...
            'Require 0 < Rpatch < 0.95*delta so the knee stays outside.');
    end

    Nr=round(ip.Results.Nr);
    Nt=round(ip.Results.Ntheta);
    if mod(Nt,2)~=0
        error('build_tip_submodel_from_global:OddNtheta', ...
            'Ntheta must be even for exact mirror pairing.');
    end

    tip=C.V2(:);
    Rgl=C.R_gl;
    Rloc=C.R_loc;

    [xloc,T,ringNode,outerVertices]=make_symmetric_cracked_disk( ...
        Rpatch,Nr,Nt,ip.Results.RadialPower);

    xgl=(Rgl*xloc.').'+tip.';

    % Perturb only non-boundary upper-side T3 nodes.  This keeps the outer
    % displacement data and both crack faces unchanged.
    [xgl,alphaUsed,idxMove]=perturb_patch( ...
        xgl,T,tip,Rloc,ip.Results.AsymmetryLevel,Rpatch/Nr);

    % Preserve the parent T3 mesh for point-location diagnostics.
    mesh=struct();
    mesh.coord3=xgl;
    mesh.connect3=T;
    [mesh.coord,mesh.connect]=T3toT6_fast(xgl,T);

    mat=Sglobal.mat;
    if ~isfield(mat,'Dmat') && isfield(mat,'D'),mat.Dmat=mat.D;end
    if ~isfield(mat,'D') && isfield(mat,'Dmat'),mat.D=mat.Dmat;end

    [nip2,xip2,w2,Nextr]=integr();
    quad=struct('nip2',nip2,'xip2',xip2,'w2',w2,'Nextr',Nextr);

    % Assemble the unconstrained local stiffness.  Dirichlet values are
    % applied by partitioning, not by row-clamping.
    K=stif_assem(mesh,mat,quad,[]);

    % Outer boundary T6 nodes: outer T3 vertices plus midside nodes of outer
    % T3 edges.  Crack-face edges are intentionally NOT fixed.
    outerT6=find_outer_T6_nodes(T,mesh.connect,outerVertices);

    Ufix=interpolate_global_displacement( ...
        Sglobal.mesh,Sglobal.U,mesh.coord(outerT6,:),tip,Rloc,Rpatch);

    ndof=2*size(mesh.coord,1);
    fixdof=reshape([2*outerT6(:)-1,2*outerT6(:)].',[],1);
    ufixdof=reshape(Ufix.',[],1);

    allDof=(1:ndof).';
    free=setdiff(allDof,fixdof);

    U=zeros(ndof,1);
    U(fixdof)=ufixdof;
    U(free)=K(free,free)\(-K(free,fixdof)*ufixdof);

    V=[(tip-Rpatch*C.e1).'; tip.'];

    P=struct();
    P.mesh=mesh;
    P.U=U;
    P.mat=mat;
    P.V=V;
    P.Rpatch=Rpatch;
    P.K=K;
    P.meshInfo=struct( ...
        'Nr',Nr,'Ntheta',Nt,'nT3nodes',size(xgl,1), ...
        'nT3elem',size(T,1),'nT6nodes',size(mesh.coord,1), ...
        'nT6elem',size(mesh.connect,1), ...
        'asymmetryRequested',ip.Results.AsymmetryLevel, ...
        'asymmetryUsed',alphaUsed,'perturbedNodes',idxMove(:));
    P.bcInfo=struct('outerT3Vertices',outerVertices(:), ...
        'outerT6Nodes',outerT6(:),'nFixedNodes',numel(outerT6));
end


function [X,T,ringNode,outerVertices]=make_symmetric_cracked_disk(R,Nr,Nt,pow)
% Local x1-x2 coordinates. theta=-pi and +pi are distinct crack-face nodes.

    X=[0,0]; % common tip
    ringNode=zeros(Nr,Nt+1);

    for j=1:Nr
        r=R*(j/Nr)^pow;
        th=linspace(-pi,pi,Nt+1).';
        ids=(size(X,1)+(1:Nt+1)).';
        X=[X; r*cos(th),r*sin(th)]; %#ok<AGROW>
        ringNode(j,:)=ids.';
    end

    T=zeros(0,3);

    % Tip fan.
    for k=1:Nt
        T(end+1,:)=[1,ringNode(1,k),ringNode(1,k+1)]; %#ok<AGROW>
    end

    % Annuli.  Mirror-related sectors use mirror-related diagonals.
    for j=1:Nr-1
        for k=1:Nt
            a=ringNode(j,k);
            b=ringNode(j,k+1);
            c=ringNode(j+1,k);
            d=ringNode(j+1,k+1);

            thetaMid=-pi+(k-0.5)*(2*pi/Nt);
            if thetaMid<0
                % diagonal a-d
                T(end+1,:)=[a,d,c]; %#ok<AGROW>
                T(end+1,:)=[a,b,d]; %#ok<AGROW>
            else
                % mirrored diagonal b-c
                T(end+1,:)=[a,b,c]; %#ok<AGROW>
                T(end+1,:)=[b,d,c]; %#ok<AGROW>
            end
        end
    end

    A=signed_areas(T,X);
    if any(A<=0)
        error('build_tip_submodel_from_global:BadTemplate', ...
            'Symmetric patch template contains non-CCW triangles.');
    end

    outerVertices=ringNode(end,:).';
end


function ids6=find_outer_T6_nodes(T3,T6,outerVertices)
    outerSet=false(max(T3(:)),1);
    outerSet(outerVertices)=true;

    ids6=outerVertices(:);
    for e=1:size(T3,1)
        v=T3(e,:);
        m=T6(e,4:6);
        edges=[v([1 2]);v([2 3]);v([3 1])];
        for q=1:3
            if outerSet(edges(q,1)) && outerSet(edges(q,2))
                ids6(end+1,1)=m(q); %#ok<AGROW>
            end
        end
    end
    ids6=unique(ids6);
end


function Uq=interpolate_global_displacement(mesh,U,Xq,tip,Rloc,Rpatch)
% Interpolate the global T6 field.  At the two crack-face endpoints use a
% tiny side-aware offset for element location so the upper and lower faces
% are not confused by coincident geometry.

    TR=triangulation(mesh.connect3,mesh.coord3);
    Xloc=(Rloc*(Xq-tip.').').';

    Xfind=Xq;
    tolSide=1e-7*Rpatch;
    nearBack=abs(Xloc(:,2))<1e-10*Rpatch & Xloc(:,1)<0;

    % Determine side by sign of the angle reconstructed from the requested
    % coordinate sequence.  If exactly on the crack line, distinguish by the
    % duplicate-node ordering using nearest local y perturbation: the first
    % occurrence is assigned lower, the second upper.
    idx=find(nearBack);
    if numel(idx)>=2
        [~,ord]=sort(Xq(idx,2)); %#ok<ASGLU>
        % Coordinates are identical; sort is stable. Split occurrences.
        half=floor(numel(idx)/2);
        idxLower=idx(1:half);
        idxUpper=idx(half+1:end);
        e2global=Rloc(2,:).';
        Xfind(idxLower,:)=Xfind(idxLower,:)-tolSide*e2global.';
        Xfind(idxUpper,:)=Xfind(idxUpper,:)+tolSide*e2global.';
    end

    [elem,bary]=pointLocation(TR,Xfind(:,1),Xfind(:,2));
    if any(isnan(elem))
        error('build_tip_submodel_from_global:InterpolationOutside', ...
            'Outer patch point not found in global parent mesh.');
    end

    Uq=zeros(size(Xq));
    for k=1:size(Xq,1)
        nodes=mesh.connect(elem(k),:);
        L1=bary(k,1);
        L2=bary(k,2);
        L3=1-L1-L2;
        N=[L1*(2*L1-1),L2*(2*L2-1),L3*(2*L3-1), ...
           4*L1*L2,4*L2*L3,4*L3*L1];
        ue=[U(2*nodes-1),U(2*nodes)];
        Uq(k,:)=N*ue;
    end
end


function [X,alphaUsed,idxMove]=perturb_patch(X0,T,tip,Rloc,alphaReq,href)
    X=X0;
    alphaUsed=0;
    idxMove=zeros(0,1);
    if alphaReq<=0,return;end

    TR=triangulation(T,X0);
    fb=freeBoundary(TR);
    boundary=unique(fb(:));
    isBoundary=false(size(X0,1),1);
    isBoundary(boundary)=true;

    xl=(Rloc*(X0-tip.').').';
    idx=find(~isBoundary & xl(:,2)>0 & hypot(xl(:,1),xl(:,2))>0.15*href);
    if isempty(idx),return;end

    phase=9.17*xl(idx,1)/href+5.31*xl(idx,2)/href;
    dloc=[0.55*sin(phase),0.85*cos(phase)];
    Rgl=Rloc.';
    dgl=(Rgl*dloc.').';

    alpha=alphaReq;
    for it=1:10
        Xt=X0;
        Xt(idx,:)=Xt(idx,:)+alpha*href*dgl;
        if all(signed_areas(T,Xt)>1e-14*href^2)
            X=Xt;
            alphaUsed=alpha;
            idxMove=idx;
            return;
        end
        alpha=.5*alpha;
    end
end


function A=signed_areas(T,X)
    v1=X(T(:,1),:);v2=X(T(:,2),:);v3=X(T(:,3),:);
    A=.5*((v2(:,1)-v1(:,1)).*(v3(:,2)-v1(:,2))- ...
          (v2(:,2)-v1(:,2)).*(v3(:,1)-v1(:,1)));
end
