function run_ci_sif_audit
%RUN_CI_SIF_AUDIT  Reduced but end-to-end SIF verification run for CI.\n% The full parameter sweep is run only after these smoke/gate checks pass.

    addpath(genpath(pwd));

    outdir=fullfile('verification','sif','outputs');
    if ~exist(outdir,'dir'),mkdir(outdir);end

    fprintf('\n=== 0. Historical one-leg old-method baseline ===\n');
    main_reproduce_historical_oneleg_baseline( ...
        'Sigma0',1.0, ...
        'rOverA',[0.30 0.50 0.60], ...
        'SaveOutputs',true, ...
        'OutputDir',outdir);

    fprintf('\n=== 1. Auxiliary-field unit tests ===\n');
    R=runtests(fullfile('verification','sif','test_SIF_auxiliary_fields.m'));
    assertSuccess(R);

    fprintf('\n=== 2. Centered-hole parity: old versus EDI ===\n');
    main_check_centered_hole_EDI_parity( ...
        'ThetaDeg',[-5 0 5], ...
        'rOverA0',[0.50 0.65], ...
        'InnerFraction',0.20, ...
        'MeshScale',0.50, ...
        'a0Factor',4.0, ...
        'SaveOutputs',true, ...
        'OutputDir',outdir, ...
        'Verbose',true);

    fprintf('\n=== 3. Two-leg full-geometry mirror sign check ===\n');
    main_twoleg_mirror_sign_check( ...
        'MeshScale',1.0, ...
        'rOverDelta',[0.30 0.50], ...
        'InnerFraction',0.20, ...
        'SaveOutputs',true, ...
        'OutputDir',outdir);

    fprintf('\n=== 4. Two-leg asymmetry audit: reduced grid ===\n');
    main_twoleg_sif_asymmetry_audit( ...
        'MeshScaleList',[1.0], ...
        'AsymmetryLevels',[0 0.20], ...
        'rOverDelta',[0.30 0.50], ...
        'EDIInnerFraction',0.20, ...
        'SaveOutputs',true, ...
        'OutputDir',outdir, ...
        'Verbose',true);

    fprintf('\n=== 5. EDI domain sensitivity: reduced grid ===\n');
    main_twoleg_edi_domain_sensitivity( ...
        'MeshScaleList',[1.0], ...
        'AsymmetryLevels',[0 0.20], ...
        'OuterOverDelta',[0.30 0.50], ...
        'InnerFractions',[0.00 0.20 0.35], ...
        'SaveOutputs',true, ...
        'OutputDir',outdir);

    fprintf('\nCI SIF audit completed.\n');
end
