function [T,V]=load_increment_comparison_run(runDir,da_mm)
% Publication input identity, not a numerical acceptance or interpolation rule.
f=fullfile(runDir,'states.csv');vf=fullfile(runDir,'vertices.csv');
assert(exist(f,'file')==2,'incfig:MissingStates','Missing %s.',f);
assert(exist(vf,'file')==2,'incfig:MissingVertices','Missing %s.',vf);
summary=fullfile(runDir,'increment_study_summary.mat');
assert(exist(summary,'file')==2,'incfig:MissingProvenance', ...
    'CSV filenames alone cannot establish the coarse-family provenance: %s',summary);
d=load(summary,'M');M=d.M;
assert(strcmp(M.study,'crack_increment_sensitivity_coarse_family')&& ...
    abs(M.increment_mm-da_mm)<=1e-12,'incfig:FamilyMismatch','Wrong increment-study source.');
expected=struct('coreScale',2,'farCapOverIncrement',1.25,'transitionOverIncrement',1, ...
    'farSlope',.15,'boundaryMetricGrowth',.35);
for name=fieldnames(expected).'
    field=name{1};value=M.controls.(field);
    assert(isnumeric(value)&&isscalar(value)&&isfinite(value)&& ...
        abs(value-expected.(field))<=1e-14,'incfig:FamilyMismatch', ...
        'Wrong coarse-family control %s.',field);
end
T=sortrows(readtable(f),'crack_length_mm');V=sortrows(readtable(vf),'crack_length_mm');
req={'segment','tip_x_m','tip_y_m','theta_deg','KI_unit','KII_unit', ...
    'KII_over_KI','delta_theta_next_deg','theta_next_deg','crack_length_mm'};
assert(all(ismember(req,T.Properties.VariableNames)),'incfig:Columns','Missing state columns.');
assert(all(ismember({'vertex','crack_length_mm','x_m','y_m'},V.Properties.VariableNames)), ...
    'incfig:Columns','Missing vertex columns.');
assert(all(all(isfinite(T{:,req})))&&all(all(isfinite(V{:,:})))&& ...
    isequal(T.segment,(1:height(T))')&&isequal(V.vertex,(0:height(V)-1)')&& ...
    height(V)==height(T)+1,'incfig:GridMismatch','Ambiguous, incomplete, or nonfinite output grid.');
% Retain the original CSV length-identity tolerance and driver geometry tolerance.
assert(all(abs(T.crack_length_mm-da_mm*T.segment)<=1e-8)&& ...
    all(abs(V.crack_length_mm-da_mm*V.vertex)<=1e-8), ...
    'incfig:IncrementMismatch','State/vertex lengths differ from the requested increment.');
assert(max(abs(T.tip_x_m-V.x_m(2:end)))<=2e-12&& ...
    max(abs(T.tip_y_m-V.y_m(2:end)))<=2e-12&& ...
    max(abs(vecnorm(diff([V.x_m,V.y_m]),2,2)-1e-3*da_mm))<=2e-12, ...
    'incfig:GridMismatch','State tips and vertex geometry are not the same solved history.');
assert(isstruct(M.Path)&&height(M.Path.stepTable)==height(T)&&all(M.Path.stepTable.pass), ...
    'incfig:ArchiveMismatch','CSV rows are not the accepted summary history.');
assert(isequal(size(M.Path.vertices),[height(V),2])&& ...
    max(abs(M.Path.vertices(:,1)-V.x_m))<=2e-12&& ...
    max(abs(M.Path.vertices(:,2)-V.y_m))<=2e-12, ...
    'incfig:ArchiveMismatch','CSV vertices differ from the authoritative summary.');
% Use the existing SIF/angle regression limits only for CSV round-trip
% identity; no physical acceptance test or extraction tolerance is changed.
for field={'KI_unit','KII_unit','KII_over_KI','theta_deg','delta_theta_next_deg','theta_next_deg'}
    name=field{1};tol=5e-10;
    if contains(name,'theta'),tol=5e-9;end
    assert(max(abs(T.(name)-M.Path.stepTable.(name)))<=tol, ...
        'incfig:ArchiveMismatch','CSV scientific column %s differs from its summary.',name);
end
end
