function validate_increment_study_p1_cache(R,candidate,R0,checkpointFile)
% The compact P1 shortcut must prove the same qualified geometry/family.
% Read only mesh/configuration/metadata, never U and never solve/replay EDI.
id='incstudy:P1ReuseMismatch';
assert(isfield(R,'pass')&&R.pass&&isfield(R,'gates')&& ...
    all(structfun(@logical,R.gates))&&isfield(R,'coreMeshControls'),id, ...
    'Cached P1 is not an accepted core-qualified result.');
a=R.coreMeshControls;b=candidate.coreMeshControls;
for name={'scale','hTip_m','rInner_m','rOuter_m','rCore_m', ...
        'expectedCoreT3','expectedEDIElements','expectedOptimizedSupport','expectedNativeSamples'}
    f=name{1};assert(isfield(a,f)&&isfield(b,f)&&isequaln(a.(f)(:),b.(f)(:)),id, ...
        'Cached P1 core/increment fingerprint differs: %s.',f);
end
assert(isfield(R,'exteriorMeshControls')&&isfield(candidate,'exteriorMeshControls')&& ...
    isequaln(R.exteriorMeshControls,candidate.exteriorMeshControls),id, ...
    'Cached P1 exterior mesh family differs.');
assert(exist(checkpointFile,'file')==2,'incstudy:P1CheckpointMissing', ...
    'Cannot prove cached P1 geometry without its physical checkpoint. Use an isolated run directory.');
s=load(checkpointFile,'mesh','mat','C','meta','a0');
assert(isfield(s,'a0')&&abs(s.a0-candidate.a0)<=1e-14&& ...
    isfield(s,'mesh')&&isequal(s.mesh.connect3,candidate.t)&& ...
    isequal(size(s.mesh.coord3),size(candidate.p))&& ...
    max(abs(s.mesh.coord3(:)-candidate.p(:)))<=1e-12&& ...
    norm(s.meta.mouth-candidate.crack.Pmid(1,:))<=2e-12&& ...
    norm(s.meta.tip-candidate.crack.Pmid(end,:))<=2e-12,id, ...
    'Cached P1 checkpoint is not the current qualified geometry.');
assert_crack_checkpoint_physics(s,candidate.mat,R0.C,id);
for field={'E','nu','ps'}
    f=field{1};assert(isequaln(s.mat.(f),candidate.mat.(f)),id,'Cached P1 material differs.');
end
assert(R.EDI.EDI_elements==b.expectedEDIElements&& ...
    R.summary.T3_nodes==size(candidate.p,1)&&R.summary.T3_elements==size(candidate.t,1)&& ...
    R.summary.T6_nodes==size(s.mesh.coord,1),id,'Cached P1 summary/mesh fingerprint differs.');
end
